### ISSUE TITLE
How can I paginate throuhgh all users? (alpha 1.0.0 release)

### ISSUE THREAD

**Issue by CoreySmithRing** [okta/okta-sdk-python#112]
The readme shows an example of paginating to get the next page but that does appear to return the "resp" object so I can then recursively run the .has_next and get all of the values. In my case I am referring to users but they use they same object for the OktaApiResponse if im not mistaken. The example shown in the readme shows 
```
if resp.has_next:
    next_users, err = await resp.next()
```
but how can I continue to iterate through all the responses to get all users for example. 

Thanks

**Comment by justinabrokwah-okta** [comment]
Hi @CoreySmithRing,

Thanks for your question! The `resp` returned in the first call will do that for you. You can continually call `resp.has_next` or `await resp.next()` on the same object to continue retrieving next pages. This way, you do not have to manage multiple response objects for each page you retrieve.

In your example, to iterate through all the responses to get all users, you would do:
```py
while resp.has_next():
        next_usr_list, err = await resp.next()
        # Do stuff with users in next_usr_list
```

I'll look to update the README to clarify this. Let me know if you have any further questions.

**Comment by CoreySmithRing** [comment]
Awesome. 

I will give that a shot. 

Thanks!

**Comment by CoreySmithRing** [comment]
The above is throwing a StopAsyncIteration exception before it returns its values. I am really new to async so I am just trying to determine how to handle that exception or if it should be handled on the module side?

**Comment by justinabrokwah-okta** [comment]
May I see the code that gave you this issue? If you call `await resp.next()` after retrieving the last page, a `StopAsyncIteration` exception will be raised as per the generator pattern in Python.

For more on the generator pattern:
- [Asynchronous Generators](https://www.python.org/dev/peps/pep-0525/)

**Comment by CoreySmithRing** [comment]
For now was just doing something simple to print all users and check out some of the functionality of this package

```
config = {
    "orgUrl": "https://<OKTA URL>",
    "token": os.getenv('OKTA_TOKEN', None)
}

## DO LOGIC HERE
async def main():
    my_okta_client = OktaClient(config)
    users, resp, err = await my_okta_client.list_users(query_params={"limit": 100, "filter": "status eq \"ACTIVE\""})

    while resp.has_next:
        next_users, err = await resp.next()
        users += next_users

    count = 0
    for user in users:
        count += 1
        print(user.profile.email, user.id, count)


if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    loop.close()
```

For context we have roughly 7k active users. I presume its a timeout of some sort on async functions but I am not very familiar with async for python at this time so I appreciate you give some guidance.

**Comment by CoreySmithRing** [comment]
This is the exception it throws as well 
```
  File "./get-all-users.py", line 31, in <module>
    loop.run_until_complete(main())
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "./get-all-users.py", line 20, in main
    next_users, err = await resp.next()
  File "/Users/username/Git/okta-sdk-python/okta/api_response.py", line 123, in next
    next_page, error = await self.get_next().__anext__()
StopAsyncIteration
```

**Comment by justinabrokwah-okta** [comment]
Thank you for providing the sample. I think the issue here resides in your check to see if there are more pages.
`while resp.has_next` should be `while resp.has_next`**()** , with the parentheses, since it is a function. 

Try that and let me know if your problem is resolved!

**Comment by CoreySmithRing** [comment]
Of course, simple solution. thank you!

**Comment by gabrielsroka** [comment]
@CoreySmithRing thanks for the example. i've added @justinabrokwah-okta 's change and made some minor changes.

```python
from okta.client import Client as OktaClient
import asyncio

async def main():
    client = OktaClient()
    users, resp, err = await client.list_users()

    while resp.has_next():
        next_users, err = await resp.next()
        users += next_users

    count = 0
    for user in users:
        count += 1
        print(user.profile.email, user.id, count)


loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

i like the code, but i'm concerned about fetching, for example, 1 million users and keeping them all in memory.

this snippet processes them as you go along. of course, if you don't have 1 million users, it may not be a concern.

```python
async def main():
    client = OktaClient()
    users, resp, err = await client.list_users()
    while True:
        for user in users:
            print(user.profile.login, user.id)
        if resp.has_next():
            users, err = await resp.next()
        else:
            break
```
