### ISSUE TITLE
Where is the new location of okta.framework.OktaError?

### ISSUE THREAD

**Issue by achantavy** [okta/okta-sdk-python#122]
First off congrats on the 1.0.0 release! :-)

We have some code that uses `OktaError` and expects to find it at `from okta.framework.OktaError import OktaError` as in your 0.0.4 release, but it looks like things have changed since 1.0.0. What is the new exception type that I should use now, and does it still have the same error codes as before? E.g. "E0000006".

Here's the error message that I get:
```
cartography/intel/okta/__init__.py:3: in <module>
    from okta.framework.OktaError import OktaError
E   ModuleNotFoundError: No module named 'okta.framework'
```

And here's the line: https://github.com/lyft/cartography/blob/2f3016bfe1cc4543c0d526fa067d166a70116b26/cartography/intel/okta/__init__.py#L3

And here's our failing CI build: https://travis-ci.org/github/lyft/cartography/builds/737221215#L529

Possibly related to 
- https://github.com/okta/okta-sdk-python/issues/5
- https://github.com/okta/okta-sdk-python/pull/10

Appreciate the help!

**Comment by bretterer** [comment]
@achantavy Thank you for the congrats!  We did make a bunch of changes in this version of the SDK.

With these changes were changes to the errors.  You can find the new error classes in the [okta/errors Directory](https://github.com/okta/okta-sdk-python/blob/master/okta/errors/)

All Okta errors will be wrapped up in the [OktaAPIError](https://github.com/okta/okta-sdk-python/blob/master/okta/errors/okta_api_error.py) class and yes, we still expose the Okta error code in the class.

Please let us know if you have any other concerns or issues with our new SDK version

**Comment by camillsir** [comment]
I'm doing a similar transition from version 0.0.4 to 1.x and discovered this change. When I tried using the new error classes I'm getting an exception.

> TypeError: catching classes that do not inherit from BaseException is not allowed

It looks like the [base error class](https://github.com/okta/okta-sdk-python/blob/master/okta/errors/error.py#L1) does not inherit from Exception or BaseException which is a [requirement](https://python.readthedocs.io/en/latest/library/exceptions.html).

**Comment by serhiibuniak-okta** [comment]
@camillsir This `Error` class wasn't designed to be an Exception. It is used just to pass specific error messages. On the other hand, your notice is really good. How did you want to use it? Maybe, it's worth to make custom exceptions.

**Comment by bretterer** [comment]
Internal Ref: OKTA-347117

**Comment by serhiibuniak-okta** [comment]
@camillsir Custom exceptions added with version 1.1.0 https://github.com/okta/okta-sdk-python#exceptions

Please let us know if you have any other concerns or issues with our new SDK version.

**Comment by serhiibuniak-okta** [comment]
I'm closing this issue as resolved. @achantavy @camillsir if you still have questions, feel free to reopen or create a new issue.
