### ISSUE TITLE
Expose request "headers" to provide additional functionality

### ISSUE THREAD

**Issue by techjutsu-mikeb** [okta/okta-sdk-python#151]
Expose the ability to provide additional "headers" (such as "X-Forwarded-For") for factor verification (example method = "verify_factor")

Some API calls have the ability to send additional headers.

I may consider forking this for a pull request.

**Comment by bretterer** [comment]
Hi @techjutsu-mikeb, thanks for the report here.  This is a good idea here. I am going to address this with our engineer for python to see what we may be able to do for this.  If you are considering a fork and PR, we would be open to taking a look as well. Just be aware, the SDK is generated through openAPI, so you would need to make sure you update the templates where necessary and re-generate the SDK code.

**Comment by techjutsu-mikeb** [comment]
That would be great if there was "official" support added for that.

**Comment by serhiibuniak-okta** [comment]
@techjutsu-mikeb Let me dig into it. 
Meanwhile, if it's a blocker, you can write/use your own RequestExecutor (as per https://github.com/okta/okta-sdk-python#extending-the-client or https://github.com/okta/okta-sdk-python#extending-or-creating-new-classes).
We need to have something like:
```py
request.add_header('header_name', 'header_value')
```
Is it correct?
I will notify when "official" support is ready.

**Comment by techjutsu-mikeb** [comment]
Thanks for the response @serhiibuniak-okta - I have no problem with the custom RequestExecutor. I need to provide the header and value only for specific API requests. I may need to use the raw API method prior to this going in.

Unless you can suggest other options?
Thank-you

**Comment by serhiibuniak-okta** [comment]
@techjutsu-mikeb I'm working on solution, which will work like the following:
```py
import asyncio

from okta.client import Client as OktaClient

async def main():
    client = OktaClient()

    # set custom headers
    client.set_custom_headers({'Custom-Header': 'custom value'})

    # perform different requests with custom headers
    users, resp, err = await client.list_users()
    for user in users:
        print(user.profile.first_name, user.profile.last_name)

    # clear all custom headers
    client.clear_custom_headers()

    # output should be: {}
    print(client.get_custom_headers())


asyncio.run(main())
```

**Comment by techjutsu-mikeb** [comment]
That looks great! Thanks. I'll be able to add custom headers per request/method execution which is what is supported by the factors verify API endpoint.

Thank-you @serhiibuniak-okta

**Comment by serhiibuniak-okta** [comment]
@techjutsu-mikeb SDK release 1.3.0 is ready. I'm closing this issue as resolved. Feel free to open a new one in case of any errors or suggestions.
