### ISSUE TITLE
allow lowercase Keys for config files

### ISSUE THREAD

**Issue by ergyjb** [okta/okta-sdk-python#161]
using a .ini file for the configs 
'orgurl' and other keys fail to come in with the CamelCase that YAML provides. 

see: https://docs.python.org/3/library/configparser.html

**Comment by arvindkrishnakumar-okta** [comment]
@ergyjb Thanks for your question! Our Python SDK team will follow-up on this after the holidays.

**Comment by serhiibuniak-okta** [comment]
Hi @ergyjb , could you please, provide more details? We use .yaml files for configuration: https://github.com/okta/okta-sdk-python#configuration-reference. If your project needs only .ini files, probably, you should convert variables to lowerCamelCase and we have such method here - https://github.com/okta/okta-sdk-python/blob/master/okta/helpers.py

**Comment by ergyjb** [comment]
No I just switched to YAML and that was better

**Comment by serhiibuniak-okta** [comment]
Glad to hear that everything is fine. Feel free to open a new issue in case of any questions.
