### ISSUE TITLE
Rate limit date format isn't handled properly and prevents hitting backoff code

### ISSUE THREAD

**Issue by JonsSpaghetti** [okta/okta-sdk-python#162]
in okta.request_executor, it seems that when you get rate limited, the server passes back a Date header that contains a string containing a date/time with an unexpected format.

It seems that string is formatted in a way that the okta.util.convert_date_time_to_seconds doesn't expect and throws an exception.

```python
if attempts < max_retries and (error or check_429):
      date_time = headers.get("Date", "")
      if date_time:
          date_time = convert_date_time_to_seconds(date_time)
```

It results in this (incomplete) stack trace:
```
Traceback (most recent call last):
   File "/usr/local/lib/python3.6/dist-packages/okta/resource_clients/application_client.py", line 1536, in assign_user_to_application
    .execute(request, AppUser)
  File "/usr/local/lib/python3.6/dist-packages/okta/request_executor.py", line 138, in execute
    _, response, response_body, error = await self.fire_request(request)
  File "/usr/local/lib/python3.6/dist-packages/okta/request_executor.py", line 176, in fire_request
    self.fire_request_helper(request, 0, time.time())
  File "/usr/local/lib/python3.6/dist-packages/okta/request_executor.py", line 229, in fire_request_helper
    date_time = convert_date_time_to_seconds(date_time)
  File "/usr/local/lib/python3.6/dist-packages/okta/utils.py", line 53, in convert_date_time_to_seconds
    DATETIME_FORMAT)
  File "/usr/lib/python3.6/_strptime.py", line 565, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.6/_strptime.py", line 362, in _strptime
    (data_string, format))
ValueError: time data 'Fri, 15 Jan 2021 05:53:21 GMT' does not match format '%Y-%m-%dT%H:%M:%S.%fZ'

```

I suggest standardizing this internally (ideally using ISO-8601 datetime format)

**Comment by serhiibuniak-okta** [comment]
@JonsSpaghetti Thank you for a detailed description of the issue. I'm looking into it. Is it a blocker? I don't see some easy workaround to unblock you, but writing own retry wrapper around request and playing with `rateLimit` configuration (set `maxRetries` to 0 to disable our retry logic):
```py
# use lib retry or write own retry logic 
from retry.api import retry_call


# assume problem is while calling method "list_users"
async def main():
    config = {'rateLimit': {'maxRetries': 0}}
    client = OktaClient(config)
    retry_call(client.list_users, tries=3)
```

**Comment by JonsSpaghetti** [comment]
@serhiibuniak-okta I saw that you posted a fix for this, thanks for the quick turnaround.  The solution you posted makes sense to me so if we need to do this immediately I'll consider setting maxRetries to 0 and using separate retry logic or something similar.

Do you have any estimate when the change will go in/be available in a published version of the SDK?

**Comment by serhiibuniak-okta** [comment]
@JonsSpaghetti The issue was in outdated date format. For easier workaround you can try reassign constant before any other import:
```py
from okta import constants
constants.DATE_FORMAT = "%a, %d %b %Y %H:%M:%S %Z"

# then rest of imports and code:
from okta.client import Client as OktaClient
```
Hope, this helps. And regarding estimates about published version: I will clarify from Monday and reply with estimations.

**Comment by serhiibuniak-okta** [comment]
@JonsSpaghetti This fix will be included in published version soon, next upcoming release.

**Comment by serhiibuniak-okta** [comment]
@JonsSpaghetti Release v1.3.2 is ready, I'm closing this issue as resolved.
