### ISSUE TITLE
Using list_group_users returns an HTTP 405 error

### ISSUE THREAD

**Issue by bnknkl** [okta/okta-sdk-python#172]
Hi all,

I'm testing out list_group_users for a new service, and it's returning a 405 error on the call:

`{'message': 'Okta HTTP 405 E0000022 The endpoint does not support the provided HTTP method'} `

The code I'm using is as follows, shortened for relevance:

```
import asyncio
from okta.client import Client as OktaClient

okta_group = redacted

okta_config = {
    'orgUrl': redacted,
    'token': redacted
}

async def okta_group_members():
    employees = []
    params = {
        'limit': 200
    }
    try:
        users, response, error = await okta_client.list_group_users(
            groupId=okta_group, query_params=params
        )
        while True:
            if users is not None:
                for user in users:
                    user_sanitized = {
                        'first_name': user.profile.first_name,
                        'last_name': user.profile.last_name,
                        'user_id': user.id,
                        'email': user.profile.email,
                        'status': user.status
                    }
                    employees.append(user_sanitized)
                if response.has_next():
                    users, error = await response.next()
                else:
                    break
            elif error is not None:
                logger.error(f'Okta API Error: {error}')
    except Exception as e:
        logger.exception(f'Error retrieving users from the group: {e}')
    return employees

async def main():
    okta_member_list = await okta_group_members()
    print(okta_member_list)

if __name__ == '__main__':
    asyncio.run(main())
```

I'm able to make this call without issues using requests, though.

**Comment by serhiibuniak-okta** [comment]
Hi, @bnknkl . Thanks for posting this issue. Usually, this kind of error appears when API endpoint accept, for example, only GET requests and we're trying to send, for example, POST request.
Also, I used your code and it works for me. Thus I need a bit more details:
1) do you use the latest version of this sdk? (1.4.0)
2) do your code works without query_params? i.e. `users, response, error = await okta_client.list_group_users(groupId=okta_group)`

**Comment by bnknkl** [comment]
Hi @serhiibuniak-okta, thank you for your response.

1. Yes, using 1.4.0
2. Code still throws the same error response when removing the `query_params=params` statement

**Comment by serhiibuniak-okta** [comment]
@bnknkl it's very strange. Can we simplify your method to double-check if the error comes from list_group_users?
Please, try to run with this method instead of that long method and check if error exists:
```py
async def okta_group_members():
    okta_client = OktaClient()
    users, response, error = await okta_client.list_group_users(groupId=okta_group)
    return users
```

**Comment by bnknkl** [comment]
I stripped it down to the block you recommended and, while it's not throwing an error anymore, it's also returning `None` as the member list, even though the group is populated.

**Comment by bnknkl** [comment]
Nevermind, I resolved this - was user error for the last piece.

Looks good from here, thank you!

**Comment by serhiibuniak-okta** [comment]
@bnknkl Thank you for confirming that everything is fine. Feel free to reopen issue or create a new one in case of any questions.
