### ISSUE TITLE
It doesn't appear to be possible to use an HTTPClient subclass

### ISSUE THREAD

**Issue by wsanchez** [okta/okta-sdk-python#177]
I'm looking to capture HTTP traffic for debugging, so I thought I might subclass `HTTPClient` as suggested in the README and some logging in `HTTPClient.send_request`…

By default it looks like [`HTTPClient` is instantiated by `RequestExecutor`](https://github.com/okta/okta-sdk-python/blob/30eacc4b1fcef91e70b63f46f1432ba560f3f06c/okta/request_executor.py#L62) and [`RequestExecutor` is instantiated by `Client`](https://github.com/okta/okta-sdk-python/blob/30eacc4b1fcef91e70b63f46f1432ba560f3f06c/okta/client.py#L112).

`Client` allows you to include a `RequestExecutor` via the `user_config` argument it is given, and uses that instead of instantiating its own.  It does not appear that `RequestExecutor` does the same with `HTTPClient`, so there is no way that I can see to use my hypothetical fancy new subclass of `HTTPClient`.

**Comment by bryanapellanes-okta** [comment]
@wsanchez ,
Thanks for reaching out! I'll ask our Python developers to take a look and reply back here.

**Comment by serhiibuniak-okta** [comment]
@wsanchez Thanks for posting this issue. In fact, we've discovered this issue too and here's a PR to fix it https://github.com/okta/okta-sdk-python/pull/176
I will post updates here.

**Comment by wsanchez** [comment]
OK that PR looks like what I need, thanks.

**Comment by wsanchez** [comment]
In case anyone needs a work-around with the current version:

```python
class _OktaLoggingHTTPClient(_OktaHTTPClient):
    """
    Okta HTTPClient subclass that adds some logging.
    """

    _log: ClassVar[Logger] = Logger()

    async def send_request(
        self, request: Dict[str, Any]
    ) -> Tuple[Any, Any, Any, Any]:
        self._log.debug("Sending HTTP request: {request}", request=request)
        return cast(
            Tuple[Any, Any, Any, Any], await super().send_request(request)
        )


class _OktaHaxxorRequestExecutor(_OktaRequestExecutor):
    """
    Okta RequestExecutor subclass that checked to make sure that its http_client
    constructor argument is actually used.
    Work-around for https://github.com/okta/okta-sdk-python/issues/177
    """

    _log: ClassVar[Logger] = Logger()

    def __init__(
        self,
        config: Dict[str, Any],
        cache: Any,
        http_client: Optional[Type[_OktaHTTPClient]] = None,
    ) -> None:
        assert http_client is _OktaLoggingHTTPClient

        super().__init__(config, cache, http_client)

        # Make sure that the passed-in http_client was used, which is not
        # the case as of okta==1.4.0
        httpClient = self._http_client  # type: ignore[has-type]
        if type(httpClient) is not _OktaLoggingHTTPClient:
            self._log.debug("Replacing HTTPClient in RequestExecutor...")
            self._http_client = _OktaLoggingHTTPClient(
                dict(
                    requestTimeout=self._request_timeout,
                    headers=self._default_headers,
                    proxy=(
                        self._config["client"]["proxy"]
                        if "proxy" in self._config["client"]
                        else None
                    ),
                ),
            )
        else:
            self._log.warning("_OktaHaxxorRequestExecutor is no longer needed")
```

**Comment by serhiibuniak-okta** [comment]
@wsanchez Nice workaround! My fix is merged to master and will be included into upcoming SDK release. Will keep you posted.

**Comment by serhiibuniak-okta** [comment]
@wsanchez SDK v1.4.1 released, I'm closing this issue as resolved. Feel free to reopen this issue if your problem still exists.
