### ISSUE TITLE
list_factors: 'FIDO' is not a valid FactorProvider

### ISSUE THREAD

**Issue by wouterhund** [okta/okta-sdk-python#185]
When doing `okta_client.list_factors` for a user which has `"provider": "FIDO"` the SDK returns the following error:

```'FIDO' is not a valid FactorProvider```

It looks like `FIDO` is not present in https://github.com/okta/okta-sdk-python/blob/master/okta/models/factor_provider.py

**Comment by arvindkrishnakumar-okta** [comment]
@bretterer can you please take a look?

**Comment by serhiibuniak-okta** [comment]
@wouterhund Thanks for posting this issue. The thing is okta-sdk-python uses a bit outdated openapi specification which is used to generate core of SDK. We're working on update. We'll keep you posted.

**Comment by techjutsu-mikeb** [comment]
This is also affecting our usage of the Okta Python SDK.

**Comment by serhiibuniak-okta** [comment]
@techjutsu-mikeb Thanks for letting us know, fix is ready, but need to be thoroughly reviewed - the change is huge. Will keep you posted.

**Comment by serhiibuniak-okta** [comment]
@wouterhund @techjutsu-mikeb SDK v1.6.0 is ready. Please us know if your issues are resolved.

**Comment by techjutsu-mikeb** [comment]
@serhiibuniak-okta - I just tested the new v1.6.0 version of the library and it appears to properly support this now.

**Comment by serhiibuniak-okta** [comment]
@techjutsu-mikeb Thanks for letting us know, I'm closing this issue as resolved.
