### ISSUE TITLE
User model lacks some fields

### ISSUE THREAD

**Issue by cobaltjacket** [okta/okta-sdk-python#19]
The user/userProfile models are lacking some important attributes. In particular, 'employeeNumber' is missing. The PowerShell scripting does have some of these other attributes. However, what would be even better is if we could utilize other fields, particularly those which we may have added on a custom basis.

**Comment by dahu33** [comment]
Same problem here... Please fix it.

**Comment by jmelberg-okta** [comment]
Hi @cobaltjacket. We apologize for the long delay.

We are currently in the process of updating this project. This includes the ability to get unmapped properties (e.g. `employeeNumber`). 

Thanks!

**Comment by cobaltjacket** [comment]
Hi there. Any update on this? Will we also be able to obtain properties that come from other directories (i.e. Active Directory)?

**Comment by jmelberg-okta** [comment]
@cobaltjacket: Thanks for following up!

We are working on providing the best solution for this. This will include storing **all** fields returned via the Okta API into all of our models. This update, along with a few others will be pushed as a `v1.0.0` release to `pypi`.

Thanks for your patience!

**Comment by cobaltjacket** [comment]
We're at 5 months since your last response. Please advise. Anyone who has commented on this or the similar issues is a paying customer who would like to have this resolved.

**Comment by joshford05** [comment]
Any update on this? We definitely need the ability to update other profile fields within the SDK.

**Comment by cobaltjacket** [comment]
It sounds as if Okta has elected to just abandon this API, rather than keep it up to date.
