### ISSUE TITLE
How to rate limit?

### ISSUE THREAD

**Issue by wsanchez** [okta/okta-sdk-python#191]
I've gone through some effort to parallelize requests (by running up to 32 simultaneously) so that I can import users as quickly as possible, and then run into rate limits.

I am currently managing this (with mixed success) by trying to manage the rate at which I throw out requests, but I would like to instead use the Okta response headers to know when I need to slow things down and when I can ramp back up, as described by the [Rate Limit Best Practices](https://developer.okta.com/docs/reference/rl-best-practices/) document, which suggests that I look for headers such as `X-Rate-Limit-Remaining` to know that I'm approaching a limit.

The python SDK documentation refers to rate limiting, but I can't figure out how to tell that I am being rate limited from the client.  Specifically, when I make a request, I get back an [`OktaAPIResponse`](https://github.com/okta/okta-sdk-python/blob/0e8a4e9af4eeab15def230a6d412a606b2d142e1/okta/api_response.py#L5) object.  That object does not have a public headers attribute (it does have a private one).

That leaves me to wait until I actually hit a limit, in which case I should be getting back an error response from the server with a `429` HTTP status code.  I don't appear to ever get this in my client, though I think the SDK is making some attempts to handle this for me, though what actually happens is that my application hangs indefinitely until I notice and force it to stop and try again.

It seems like access to the headers in a non-error response is important. How can I get to them? Can you confirm whether I should be seeing an error in my client when I hit a rate limit?

**Comment by serhiibuniak-okta** [comment]
@wsanchez Thanks for paying attention to issues with rate limits, let's clarify everything step by step.
1) yes, currently you can access headers only via private attribute `_headers` of response object; 
2) sdk handles 429 error automatically and waits for some time before automatic retry, nothing is being logged so far; wait time is calculated by the following formula `retry_limit_reset - date_time + 1`, where `retry_limit_reset` comes from header `x-rate-limit-reset` and `date_time` - from header `Date`. If it seems like hanging indefinitely, then, probably, wait time is enormous. In this case, I suggest to add logs to retry logic (I will add logs too, so they will be functioning in the upcoming sdk release).
3) currently, you can't see a rate limit error, so, again, we are going to add some logs there (the only possible way to see this error now - if all retries fall into rate limit error)

Is this a blocker? Maybe, we can find some workaround for you, while waiting for a new release.

**Comment by serhiibuniak-okta** [comment]
What I'm thinking about - is that something might be wrong with dates and calculations. For example, most European countries had timeshifting past Sunday due to Daylight Saving Time, so it could also affect the calculation. I'll add logs soon, but you can do it for yourself to check wait time:
https://github.com/okta/okta-sdk-python/blob/master/okta/request_executor.py#L247-L250

**Comment by wsanchez** [comment]
OK, in case it matters: the testing I did that hung was before the DST change.

**Comment by serhiibuniak-okta** [comment]
Thanks for that information, we'll figure out what's wrong.

**Comment by serhiibuniak-okta** [comment]
@wsanchez SDK v1.5.1 is ready. Could you please, enable logs and run your tests again? Then we'll continue investigate why it  hangs.

**Comment by serhiibuniak-okta** [comment]
@wsanchez I can't figure out what might be wrong without any logs from your side. Does the problem still exist? I'm going to close this issue as stalled.

**Comment by serhiibuniak-okta** [comment]
@wsanchez  I'm closing this issue. Feel free to reopen this issue or create a new one if your problem still exists.
