### ISSUE TITLE
Need a way to copy a UserProfile object

### ISSUE THREAD

**Issue by wsanchez** [okta/okta-sdk-python#194]
The docs for updating a user say that one should fetch the user from Okta, then take, the `UserProfile` from the retrieved `User` object, and then create a new `User` with that modified profile.

The problem with that process is that it mutates the original user's profile.  I'd like to be able to create the modified profile from a copy of the original, so I don't modify the original, which might have unintended consequences for the caller that passed the user in.

I've tried this:

```python
newProfile = UserProfile(user.as_dict()["profile"])
```

But this seems to mangle the custom fields we are using (`wp_siteurl` becomes `wpSiteurl`), and then I an error from the update request: (Property name 'wpSiteurl' is not defined in profile).

**Comment by bryanapellanes-okta** [comment]
@wsanchez,
Thanks for bringing this to our attention!  I've added an item to the backlog for review and prioritization.  Our python developers will take a look and comment when we have more to share.

Thanks for using Okta!

**Comment by wsanchez** [comment]
I'm using this now:

```python
newProfile = copy.deepcopy(user.profile)
```

But I'm still running into the name mangling issue, so perhaps my issue is unrelated to copying.

The problem is that when I do something like this:

```python
user = await client.list_users(search=…)
newProfile = copy.deepcopy(user.profile)
profile.wp_siteurl = "http://haxxor/u/99632"
newUser = User(dict(id=user.id, profile=newProfile))
await client.update_user(user.id, newUser)
```

Which yields an error:

```console
	profiles.okta._exceptions.OktaAPIError: Okta HTTP 400 E0000001 Api validation failed: userProfile
	Property name 'wpSiteurl' is not defined in profile
```

I'm logging the request, and it looks like this:

```console
{'method': 'PUT', 'headers': {'Accept': 'application/json', 'Content-Type': 'application/json', 'User-Agent': 'okta-sdk-python/1.4.1 python/3.9.1 Darwin/20.3.0', 'Authorization': 'REDACTED'}, 'url': 'https://OKTA_HOST/api/v1/users/00uhlyexeeePoXFLp1d6', 'data': {'id': '00uhlyexeeePoXFLp1d6', 'profile': {'email': 'dvance669040@mailinator.com', 'firstName': 'Donovan', 'lastName': 'Vance', 'login': 'dvance669040', 'bpguid': '97ed27b2-90fb-4be2-9b12-b6fbb5477756', 'wpid': '99632', 'wpSiteurl': 'http://haxxor/u/99632'}}}
```

Note that setting `profile.wp_siteurl` ended up sending a profile attribute named `wpSiteurl` instead of `wp_siteurl`.

**Comment by wsanchez** [comment]
Note I also tried avoiding this by not updating the `wp_siteurl` on updated users for now, but this fails anyway: if the user has that attribute set in Okta already, then when I fetch the user record and try to update it with a different changed attribute, I still see the above error.

**Comment by serhiibuniak-okta** [comment]
@wsanchez Thanks for providing a lot of details, investigating is much easier now. It is true that all attributes in UserProfile model are being converted to lowerCamelCase before request. So, as a workaround temporarily, you can use simple dict instead of model, i.e. 
```py
# dict instead of newUser
await client.update_user(user.id, {'firstName': 'Donovan', 'wp_siteurl': 'http://haxxor/u/99632', ... here comes rest of attrs})
```
Meanwhile, we'll work on this problem. Will keep you posted.

**Comment by wsanchez** [comment]
OK that works.  One correction: the second argument isn't the profile dict, but a user dict:

```python
await client.update_user(user.id, {'id': user.id, 'profile': {'firstName': 'Donovan', ...}})
```

**Comment by serhiibuniak-okta** [comment]
@wsanchez SDK v1.6.0 is ready. I'm closing this issue as resolved. Feel free to reopen this issue or create a new one if your problem still exists.
