### ISSUE TITLE
Unable to set value for custom attribute that was previously empty/null with update_user

### ISSUE THREAD

**Issue by warrenySC** [okta/okta-sdk-python#201]
I am seeing this behavior when following the code sample from https://github.com/okta/okta-sdk-python#update-a-user

Repro steps:
1. Create a custom attribute for the Okta profile
2. Create a user in Okta admin dashboard
3. Update the user profile using the SDK with code snippet below
4. Observe that the attribute was not updated
5. Edit the Okta profile in the UI and give the attribute a random value
6. Re-run the code snippet
7. Observe that the attribute has been updated

```
async def main():
    client = okta_client

    user, resp, err = await client.get_user('{user_id}')

    new_profile = user.profile
    new_profile.custom_attr= 'Foo'

    updated_user_obj = models.User({'profile': new_profile})
    print(updated_user_obj)
    # Update User with new details
    updated_user, _, err = await client.update_user(user.id, updated_user_obj)
    print(updated_user)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

**Comment by aarongranick-okta** [comment]
@warrenySC Thank you for the report. One of our Python engineers will investigate. (internal ref: OKTA-393273)

**Comment by serhiibuniak-okta** [comment]
@warrenySC Thanks for providing a lot of details. As a temporary workaround you can try:
```py
new_profile.custom_attr = 'Foo'
new_profile.custom_attributes.append("custom_attr")
```

Let me know if it works for you. Meanwhile, I'll investigate this issue.

**Comment by serhiibuniak-okta** [comment]
@warrenySC SDK v1.7.0 has been released. Now you can use custom attributes as usual. I'm closing this issue as resolved. Feel free to reopen this issue or create a new one if your problem still exists.
