### ISSUE TITLE
Remove flatdict requirement

### ISSUE THREAD

**Issue by martinvelez** [okta/okta-sdk-python#203]
Many companies require internal approval before using an open source pip package.  Often, the internal approver has to review not only the package but also the other pip package it depends on.  

For example, I noticed that this project depends on `flatdict`.  I see that this is used to help prune the config.  Could that dependency be removed?  I figure the _prune_config method could be written without it and this package can "prune" it's dependencies.

https://github.com/okta/okta-sdk-python/blob/46184663baccb926dc14ab964dfd9406d375de0a/okta/config/config_setter.py#L66

https://github.com/okta/okta-sdk-python/blob/46184663baccb926dc14ab964dfd9406d375de0a/okta/config/config_setter.py#L72

**Comment by bryanapellanes-okta** [comment]
@martinvelez,
Thanks for reaching out!  I'll bring your request to the attention of our python developers.  Someone will respond here with more. 

Thanks for using Okta!

**Comment by martinvelez** [comment]
I didn't see the other usages of FlatDict in the Github search results.  I see them now looking at https://github.com/okta/okta-sdk-python/blob/master/okta/config/config_setter.py.  I understand that removing a dependency can be non-trivial and it might be in this case.  

I just wanted to bring to your attention that adding some dependencies like `flatdict` solves an engineering problem but potentially introduces other problems (incompatible version, licenses, etc.) as companies evaluate `okta-sdk-python`.

With that said, you are right, it is a balance.  I defer to you.  If you like, we can close this issue.

**Comment by serhiibuniak-okta** [comment]
I've got your point too. First of all, thanks for attracting our attention to this, we really appreciate this.
At this point, I consider this issue as non-critical, but we'll keep it in mind.
I see several ways how to deal with this:
1) we'll take a look at it after fixing all critical issues
2) if it is critical for you, any contribution is welcome, i.e. you can provide your own solution: we'll review it and merge to our codebase if everything is fine. Here's the contributing guide: https://github.com/okta/okta-sdk-python/blob/master/CONTRIBUTING.md

Again, thanks for paying attention to details and let us know if it works for you.

**Comment by martinvelez** [comment]
Yes, this works.  If I have time.  I'll take a shot at it.
