### ISSUE TITLE
Pagination yields inconsistent data between first request and subsequent requests

### ISSUE THREAD

**Issue by explody** [okta/okta-sdk-python#210]
Version: 1.6.0
Python: 3.8.2

The scenario is that when fetching application users, I noticed that in the returned items from the initial request, each AppUser had the "_links" attribute, but in the data set from response.next(), "_links" was missing.  I confirmed that manually doing API calls, all returned items had the "_links" key, in first and subsequent pages.

Digging into the code, I found this in application_client.py:

https://github.com/okta/okta-sdk-python/blob/46184663baccb926dc14ab964dfd9406d375de0a/okta/resource_clients/application_client.py#L1493-L1498

As each item is added to the result list, it's run through `APIClient.form_response_body()`.  This normalizes the dict keys and changes '_links' to 'links', which is where the problem comes in.

Yet, in api_response.py, where the pagination methods are, the items are added without `form_response_body()`

https://github.com/okta/okta-sdk-python/blob/46184663baccb926dc14ab964dfd9406d375de0a/okta/api_response.py#L126-L130

The result is, when one does `list_application_users()` (and presumably any other pagination), the items in the *first* response have keys  like this:

```python
dict_keys(['_links', 'created', 'credentials', 'id', 'lastUpdated', 'profile', 'scope', 'status', 'statusChanged', 'syncState'])
```

While items returned by next() have keys like this:

```python
dict_keys(['created', 'credentials', 'id', 'lastUpdated', 'profile', 'scope', 'status', 'statusChanged', 'syncState'])
```

Where '_links' is just gone.

Over in the app_user.py model, in __init__(), links are handled like this, where it expects the incoming config to have a 'links' key, which _only_ would be there if the item went through `form_response_body()` first.

https://github.com/okta/okta-sdk-python/blob/46184663baccb926dc14ab964dfd9406d375de0a/okta/models/app_user.py#L38-L39

I'm not sure how you'd want to fix this... one could either run paginated requests through `form_response_body()` or change how the model is instantiated, to handle keys of both "links" *or* "_links". The former could be a central change in api_response.py while the latter would probably mean modifying every model, so I presume the first option would be better.

I'm happy to do a PR, with some guidance to which approach to take.

**Comment by serhiibuniak-okta** [comment]
@explody Thanks for this issue with providing a lot of details. And yes, this problem looks like a non-trivial one, need to think a bit. 
You can do a PR, but you'll need to sign CLA https://developer.okta.com/cla/ in order to accept your PR

**Comment by explody** [comment]
I submitted a PR that changes form_response_body to a static method, and uses that for paginated results - all tests pass and it's working fine for me locally but yes, it's potentially complicated.

In any case, I just sent a signed CLA over to your folks, so do whatever you like with it ;)

**Comment by serhiibuniak-okta** [comment]
Thanks @explody , I'll investigate a bit deeper the problem and will review your PR.

**Comment by serhiibuniak-okta** [comment]
@explody SDK v1.7.0 has been released, I'm closing this issue as resolved.
