### ISSUE TITLE
Support for Okta ASA?

### ISSUE THREAD

**Issue by jensenbox** [okta/okta-sdk-python#216]
Are there plans to support Okta ASA? I would like to have programmatic access with Python. Perhaps there is a different repository or PyPi package that I missed?

**Comment by monde** [comment]
Thanks for question @jensenbox . I will look into this additional details and get back to you here.

**Comment by serhiibuniak-okta** [comment]
@jensenbox Currently, we don't have anything for Python to work with ASA. Regarding plans to support - we're discussing it, will get back to you when we have more details.

**Comment by bjr-okta** [comment]
At this point, we will not be doing any kind of support with Python and ASA.  If this is a need for your project, please reach out to support@okta.com with a feature request.
