### ISSUE TITLE
Missing X-Rate-Limit-* headers in response

### ISSUE THREAD

**Issue by nimrodeli** [okta/okta-sdk-python#218]
Hey, 
I was trying to check the **X-Rate-Limit-*** rates during requests (because we have 2 APIs using the same Okta account and we want to be aware of it) but I saw that you replace the response headers with the request. 
`OktaAPIResponse::__init__
 self._headers = req["headers"]`

Not sure if it's a bug or by intention but I'd like to have these headers' values without patch any code from the SDK :)

**Comment by serhiibuniak-okta** [comment]
@nimrodeli Thanks for posting this issue. Those headers are used for pagination, i.e. for the next request. But, I agree, this looks a bit weird and response headers aren't available. I'm thinking about adding attribute `_resp_headers` to `OktaAPIResponse` object. Will it work for you?

**Comment by nimrodeli** [comment]
Yes, sounds good.
it will solve the issue for me.

**Comment by serhiibuniak-okta** [comment]
SDK v2.0.0 has been released, I'm closing this issue as resolved.
