### ISSUE TITLE
support org api

### ISSUE THREAD

**Issue by fawaf** [okta/okta-sdk-python#220]
https://developer.okta.com/docs/reference/api/org/

**Comment by serhiibuniak-okta** [comment]
@fawaf Thanks for posting this issue. We'll need to plan this and update openapi spec first (all Okta SDKs are generated according to common openapi spec). I'll post here when I get more details.

**Comment by serhiibuniak-okta** [comment]
@fawaf I've got more details: we will add support for org api soon. I'll post here when it is ready.

**Comment by serhiibuniak-okta** [comment]
@fawaf SDK v2.2.0 has been released. ORG API is supported now, except org logo uploading. This operation needs some extra codebase changes. You can track progress here: https://github.com/okta/okta-sdk-python/pull/244

**Comment by serhiibuniak-okta** [comment]
@fawaf SDK v2.3.0 has been released. ORG API is fully supported, I'm closing this issue as resolved. Feel free to reopen this issue or create a new one if your problem exists still.
