### ISSUE TITLE
Guidance: Rate Limiting

### ISSUE THREAD

**Issue by exitcode0** [okta/okta-sdk-python#225]
Similar to a previous issue that went stale https://github.com/okta/okta-sdk-python/issues/191

i'd like access or guidance on rate limiting my requests
the SDK supports retries and logs when rate limits are exceeded, which is fantastic.
but ideally i'd like to avoid hitting rate limits in the first place

i'm using asyncio.gather with semaphores to limit the number of async tasks in the event loop
however this leads to large batches of requests being sent until rate limits are exceeded, at which point the SDK's built in retry is helpful 
however I feel like a better solution here would be to send my requests at a consistent rate that is within the rate limits

with access to `X-Rate-Limit-Limit`, `X-Rate-Limit-Remaining`, and `X-Rate-Limit-Reset` im hoping I could write my code to respect these rate limits and adjust the rate at which I fire request based upon the content in the response headers

**Comment by serhiibuniak-okta** [comment]
Hi, @exitcode0 . You can access response headers by calling method "get_headers" upon response object. Do you need anything else?

**Comment by exitcode0** [comment]
`resp.get_headers()` throws the following error
```
sh-3.2$ /usr/local/bin/python3 /Users/<USERNAME>/code/rate_limit_testing.py
Traceback (most recent call last):
  File "/Users/<USERNAME>/code/rate_limit_testing.py", line 30, in <module>
    loop.run_until_complete(main())
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/<USERNAME>/code/rate_limit_testing.py", line 24, in main
    print(resp.get_headers())
AttributeError: 'OktaAPIResponse' object has no attribute 'get_headers'
```

`print(resp._headers)` does run successfully, however doesn't contain the headers I'm after
```
sh-3.2$ /usr/local/bin/python3 /Users/<USERNAME>/code/rate_limit_testing.py
{'User-Agent': 'okta-sdk-python/1.7.0 python/3.9.6 Darwin/20.5.0', 'Accept': 'application/json', 'Authorization': '<APIKEY>', 'Content-Type': 'application/json'}
--- script took 2.581261157989502 seconds ---
sh-3.2$ 
```

**Comment by serhiibuniak-okta** [comment]
@exitcode0 Do you use the latest sdk version? This feature appears in v2.0.0 https://github.com/okta/okta-sdk-python/releases/tag/2.0.0

**Comment by exitcode0** [comment]
🤦 
This fixed my issue, thanks for your patience and assistance on this one

**Comment by serhiibuniak-okta** [comment]
Thank you for letting us know that your issue is resolved. And thanks for using Okta! :)
