### ISSUE TITLE
Guidance needed please: Flask App with Okta integrated

### ISSUE THREAD

**Issue by gaelletjat** [okta/okta-sdk-python#226]
Hello team,
I have been working on integrating the sample shared with the Flask app I am currently building. Thank you for the samples.
Everything works fine when I use the sample code as it is.
But my app has a different structure than the one shared.
A sample tree of the app look like this:
```
myappFolder /
    venv/
    app/
        templates/
        static/
        __init__.py
        routes.py
        config.py
        handlers.py
        helpers.py
        user.py
    run.py
```
I moved the login_manager import and instantiation  into `__init__.py`
I kept the `APP_STATE, NONCE`, login and logout into` routes.py`. I am planning on moving them into __init__.py.
`run.py` imports app from myappFolder and run the `__if__name__== '__main__': app.run()`

When I run `flask run` in the command line, the app is successfully deployed. 
However, when I try to access the app on localhost, I run into a 
`RuntimeError: there is no current event loop in the thread 'Thread-9'` If I refresh (SHIFT + CMD + R), the thread number changes but the error remains the same.

I am currently looking into [flask docs](https://flask.palletsprojects.com/en/2.0.x/async-await/).
Could you please advise?
PS: I am a newbie in python-flask so I might not understand the most obvious.
Thank you

**Comment by gaelletjat** [comment]
I read the documentation for [flask async and await](https://flask.palletsprojects.com/en/2.0.x/async-await/).
I commented/deleted line 7 and replaced the `loop.run_until_complete` on line 13 and 23 in `helpers.py` with `asyncio.run(jwt_verifier...)` and apparently it's working.
I will update the issue if I am running anything after deploying on production.

**Comment by serhiibuniak-okta** [comment]
Hi @gaelletjat, thank for posting well-detailed issue. Btw, it looks like it should be under flask samples repo - https://github.com/okta/samples-python-flask/issues, but it's fine. So, currently, everything works?

**Comment by serhiibuniak-okta** [comment]
I'm closing this issue as stalled. Feel free to reopen this issue or create a new one if your problem exists still.
