### ISSUE TITLE
Unable to configure via environment variables

### ISSUE THREAD

**Issue by jensenbox** [okta/okta-sdk-python#228]
Is there a specific reason why there is no provision for configuring the client with Environment Variables?

This would allow for a cleaner implementation of https://12factor.net 

Seems like it would be very easy to implement a set of default in the `_DEFAULT_CONFIG` variable in the `ConfigSetter` class.

**Comment by jensenbox** [comment]
Actually, I see the root of the issue - the suggested documentation links are either stale or wrong. When getting a client with no parameters specified and you have not configured the client in any other way you get the following:

```core_1  | ValueError: 
core_1  | Errors:
core_1  | Your Okta URL is missing. You can copy your domain from the Okta Developer Console. Follow these instructions to find it: https://developer.okta.com/docs/guides/find-your-domain/overview
core_1  | Your Okta API token is missing. You can generate one in the Okta Developer Console. Follow these instructions: https://developer.okta.com/docs/guides/create-an-api-token/overview```

Those links should instead link to https://github.com/okta/okta-sdk-python#configuration-reference

Additionally, I would suggest that the first example on the Readme NOT have a dict based configuration - instead change the usage to not have the dict but instead mention that you need to configure the client in the following ways - in order of resolution - meaning which one will be chosen once found.

1. Configuration YAML file in the Users home directory
2. Configuration YAML file in the Application directory
3. Environment variables
4. Client constructor

Each of the above would go to a specific section hyperlink in the document. By placing this in front of the first sample it will be much clearer that configuration is a required step.

IMHO - one should never advocate the usage of the client constructor.

**Comment by serhiibuniak-okta** [comment]
@jensenbox Thanks for posting this issue, but I'd like to clarify few moments:
1) "the suggested documentation links are either stale or wrong" - could you please point which links are stale or wrong?
2) Do you mean by the first example on the README the first sample in this section - https://github.com/okta/okta-sdk-python#getting-started? It's just a starting point and right under this sample we have the following paragraph with link to confifuration:
```
Using a Python dictionary to hard-code the Okta domain and API token is encouraged for development; In production, you should use a more secure way of storing these values. This library supports a few different configuration sources, covered in the configuration reference section.
```

**Comment by serhiibuniak-okta** [comment]
I'm closing this issue as stalled. Feel free to reopen or create a new one if your problem exists still.
