### ISSUE TITLE
Non-Async version of functions?

### ISSUE THREAD

**Issue by jensenbox** [okta/okta-sdk-python#229]
Hi,

I can certainly appreciate the implementation of async in a library however in most cases that I would use this library I am using in a simple script where I am not having a significant number of simultaneous requests and therefore am completely happy with good old fashioned sync calls.

The overhead required to just call something as simple as `client.list_users()` in a non-async script is just overkill.

I would love to see a situation where you either wrap the current async functions with a prefixed `sync_` or perhaps have the current methods as sync and have another set in the same module that are postfixed with `_async` to designate that they are async.

This would make things a whole lot easier.

Thanks!

**Comment by arvindkrishnakumar-okta** [comment]
@jensenbox Thanks for posting! 

I'll have this one reviewed by one of our team members. 

cc: @serhiibuniak-okta

**Comment by serhiibuniak-okta** [comment]
@jensenbox That makes sense, but SDK uses async http requests under the hood. So, what the solution might be in current situation? I think about converting async calls to sync calls, i.e. call async method and wait for completion:
```
import asyncio

asyncio.run(client.list_users())  # this will be executed in a sync manner
```
You can use it as a temporary (or not) workaround. I think, it's pretty easy to use in client code. It is much harder to make SDK support sync calls out-of-the-box. But we will take this into account, I'll post here if we plan to support sync calls in the future. Another approach for client code - use some library like https://github.com/miyakogi/syncer

**Comment by serhiibuniak-okta** [comment]
I'm closing this issue as stalled. Feel free to reopen this issue or create a new one if your problem exists still.
