### ISSUE TITLE
Support for custom Group attributes

### ISSUE THREAD

**Issue by jensenbox** [okta/okta-sdk-python#230]
We are in the process of investigating the use of custom attributes on groups. It appears that the current `GroupProfile` class does not support this as of yet.

Is there any intention of allowing the Groups to receive the custom attributes on the `profile`?

**Comment by arvindkrishnakumar-okta** [comment]
@jensenbox Thanks for posting!

@serhiibuniak-okta - can you help with this one?

**Comment by RamaHood** [comment]
this is also the issue that we got into to integrate with okta sdk,

**Comment by serhiibuniak-okta** [comment]
@jensenbox @RamaHood SDK v2.2.0 has been released. Manage custom group attrs: https://github.com/okta/okta-sdk-python#manage-group-schema-custom-atributes
