### ISSUE TITLE
End user and admin notes are missing from the "Application" model

### ISSUE THREAD

**Issue by hb3b** [okta/okta-sdk-python#232]
When listing applications directly from the Okta API, the response includes `admin` and `enduser` notes, however, these values are not returned when using the `list_applications` function in this SDK.

**Comment by serhiibuniak-okta** [comment]
@hb3b Thank you for posting this issue. Surprisingly, `notes` attribute is not described in our openapi spec. I'll find out and come back to your issue soon.

**Comment by serhiibuniak-okta** [comment]
I can confirm that sample Bookmark app includes notes within SDK response.

**Comment by serhiibuniak-okta** [comment]
I'm closing this issue as stalled. Feel free to reopen this issue or create a new one if your problem exists still.
