### ISSUE TITLE
Does list_group_users() support filtering for ACTIVE users?

### ISSUE THREAD

**Issue by jnalley** [okta/okta-sdk-python#245]
I am trying to query for ACTIVE members of a group.  I am passing `{"filter": 'status eq "ACTIVE"'}` as the `query_params` argument to `list_group_users()` but the results seem to contain both active and inactive users.

Using the same filter with `list_users()` works with no issues.

Thanks!

**Comment by jnalley** [comment]
Oops - sorry - read the method definition and I see that `query_params.filter` is not listed.

I also noticed that `{"filter": 'status ne "ACTIVE"'}` doesn't work with `list_users()`

It returns the error: `{'message': 'Okta HTTP 400 E0000031 Invalid search criteria.\n'}`

**Comment by serhiibuniak-okta** [comment]
@jnalley Thank for posting this issue. In fact, filter works, but has some limitations: https://developer.okta.com/docs/reference/api/users/#list-users-with-a-filter
Feel free to reopen this issue or create a new one if your problem exists still.

**Comment by jnalley** [comment]
@serhiibuniak-okta I realize that `list_users()` works with a filter, but `list_group_users()` does not appear to.  This is unfortunate since my organization has been using Okta for quite some time and we have a large number of users that have been "DEPROVISIONED".  This means I get hundreds of extra (inactive) results when querying members of a group.  Relevant documentation: https://developer.okta.com/docs/reference/api/groups/#list-group-members

I tested with curl using the endpoint: `https://${myOrg}/api/v1/groups/${myGroupId}/users` to confirm that the list of returned users contains both "ACTIVE" and "DEPROVISIONED" users.  Adding a `filter` parameter doesn't seem to make a difference.
 
It seems strange that default behavior for listing all users is different than the behavior when listing members of a group.

From the docs on list-users:

```
Note: This omits users that have a status of DEPROVISIONED. To return all users, use a filter query instead.
```

**Comment by serhiibuniak-okta** [comment]
@jnalley I agree, that's strange, but `groups` and `users` - different apis. And, unfortunately, `list_group_users()` doesn't support filter so far.
