### ISSUE TITLE
Allow custom SSL deployments

### ISSUE THREAD

**Issue by mm-irvingleonard** [okta/okta-sdk-python#255]
Your library assumes a "correctly configured" underlying environment, SSL wise. Porting this kind of settings across operating systems and deployments is far from trivial, enter the SSL contexts. The builtin `ssl` module handles SSL contexts which would be basically that: an SSL configuration environment.

The current code ultimately calls `aiohttp.request` which the *aiohttp* project calls [Basic API](https://docs.aiohttp.org/en/stable/client_reference.html#basic-api) and doesn't support several features including custom SSL settings. The main change would be to migrate that line in [send_request](https://github.com/okta/okta-sdk-python/blob/92f4d20dea4ceec07945ead5d062797103f3628a/okta/http_client.py#L70) to use [aiohttp.ClientSession().request](https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientSession) instead (which looks like a drop in replacement for this case) and modify all the configuration handling code to pass a new `ssl_context` setting.

**Comment by mm-irvingleonard** [comment]
The solution in the current version would be to implement a custom `HTTPClient` class that handles the SSL context the way you want and pass it to the `okta.client.Client` constructor as the `httpClient` parameter.

```
import okta.client
import okta.http_client

class HTTPClient(okta.http_client.HTTPClient):
	
	def __init__(self, http_config={}):
		
		super().__init__(http_config)
		
		self._ssl_context = ssl.SSLContext()
		# anything else that you need to do with the context
	
	async def send_request(self, request):
		try:
			okta.http_client.logger.debug(f"Request: {request}")
			# Set headers
			self._default_headers.update(request["headers"])
			# Prepare request parameters
			params = {'method': request['method'],
					  'url': request['url'],
					  'headers': self._default_headers}
			if request['data']:
				params['data'] = json.dumps(request['data'])
			json_data = request.get('json')
			# empty json param may cause issue, so include it if needed only
			# more details: https://github.com/okta/okta-sdk-python/issues/131
			if json_data:
				params['json'] = json_data
			if self._timeout:
				params['timeout'] = self._timeout
			if self._proxy:
				params['proxy'] = self._proxy
			params['ssl_context'] = self._ssl_context
                         # Fire request
			async with aiohttp.ClientSession().request(**params) as response:
				return (response.request_info,
						response,
						await response.text(),
						None)
		except (aiohttp.ClientError, asyncio.TimeoutError) as error:
			# Return error if arises
			okta.http_client.logger.exception(error)
			return (None, None, None, error)

okta_client = okta.client.Client({'orgUrl' : 'my url', 'token' : 'theAPItoken', 'httpClient' : HTTPClient})

```

**Comment by mm-irvingleonard** [comment]
@serhiibuniak-okta with the [proposed PR](https://github.com/okta/okta-sdk-python/pull/254) it will remove the need to reimplement the `send_request` method.

**Comment by serhiibuniak-okta** [comment]
@mm-irvingleonard Thank you for providing a lot of details, I'll take a closer look soon.

**Comment by serhiibuniak-okta** [comment]
@mm-irvingleonard SDK v2.3.0 has been released. I'm closing this issue as resolved. Feel free to reopen this issue or create a new one if your problem exists still. You can find in README a sample which demonstrates how to pass SSLContext to OktaClient: https://github.com/okta/okta-sdk-python#other-configuration-options
