### ISSUE TITLE
from okta import UsersClient

### ISSUE THREAD

**Issue by moisefr** [okta/okta-sdk-python#265]
installed okta 
Tried running this code
`from okta import UsersClient`
Not working. What's the latest version of UsersClient?

**Comment by serhiibuniak-okta** [comment]
@moisefr Correct import would be:
```py
from okta.client import UserClient
```
But it won't be able to call api methods as we pass request_executor instance to all api clients from main client, so ideally, you need to do the following:
```py
from okta.client import Client

async def test_user_client():
    client = Client()
    users, _, err = await client.list_users()   # list_users - method from UserClient
```

**Comment by serhiibuniak-okta** [comment]
@moisefr I'm closing this issue as stalled. Feel free to reopen this issue or create a new one if your problem exists still.
