### ISSUE TITLE
Support for Django Rest Framework

### ISSUE THREAD

**Issue by JimJohnsonColgate** [okta/okta-sdk-python#266]
I am developing an application and attempting to use this SDK with Django Rest Framework (DRF) to call the Okta API. When making calls to the Okta Client, the function is returning a coroutine object instead of the proper data. 

As of yet DRF does not support asynchronous functionality, but it seems like it should not have to retrieve information from Okta synchronously.

I can see this was brought up once before, here:
- https://support.okta.com/help/s/question/0D54z00006yR1MS/okta-django-rest-framework-integration?language=en_US

This works fine for me using the normal requests python library to make API calls to Okta.

**Comment by serhiibuniak-okta** [comment]
@JimJohnsonColgate Thank you for posting this issue. 
This SDK was designed to work asynchronously, but there are few ways how to wrap/convert async to sync, for example it was brought up here: #229 
If you need to make it in "Django-style" and DRF does not support async, you can use their workarounds like the following:
 https://docs.djangoproject.com/en/3.1/topics/async/#sync-to-async
 
Does it work for you?

**Comment by JimJohnsonColgate** [comment]
Thanks! I missed that, and it appears to work fine.

Two other quick comments:

- Environment variables are not working for me in Django. os.getenv('OKTA_CLIENT_ORGURL'), for example, returns None. The okta client is working so I know it is accessing the yaml file, but the variables are not added in the local environment. Am I using that incorrectly? Perhaps consider adding an example to the readme section if so.
- Are local environment variables in the yaml config supported? For example, I do not want to hard-code an API token. I would generally set it up as a local variable in the container the app is running in. But using token: ${OKTA_API_KEY} in the config file does not appear to work. I can set it manually in each instance:
`client = OktaClient({'token': os.getenv('OKTA_API_KEY')})`
but it seems clunky.

**Comment by serhiibuniak-okta** [comment]
@JimJohnsonColgate README has this section https://github.com/okta/okta-sdk-python#configuration-reference which explains how to config everything you might need. Pay attention to naming and overriding. If your problem exists still, please share some code so I can reproduce it and help.

**Comment by serhiibuniak-okta** [comment]
@JimJohnsonColgate I'm closing this issue as stalled. Feel free to reopen this issue or create a new one if your problem exists still. Thanks for using OKTA!
