### ISSUE TITLE
reuse aiohttp ClientSession for better performance

### ISSUE THREAD

**Issue by gabrielsroka** [okta/okta-sdk-python#267]
https://github.com/okta/okta-sdk-python/blob/ec793a4c0ec98c679617b5bac0bc91ae13eb02d4/okta/http_client.py#L78
looks like it creates a new `aiohttp.ClientSession` for each call. this will tear down the http/tcp/ip connection and rebuild it each time, which slows down performance

here's an example using raw `aiohttp` -- note the `ClientSesion` is created once and reused:
```python
import aiohttp
import asyncio
import time

# Set these:
org_url = 'https://....oktapreview.com'
token = '...'
max_pages = 10

async def main():
    headers = {
        'Authorization': f'SSWS {token}',
        'Accept': 'application/json',
    }
    start = time.time()
    pages = 0
    async with aiohttp.ClientSession(headers=headers) as session:
        url = f'{org_url}/api/v1/users'
        while url:
            async with session.get(url) as resp:
                users = await resp.json()
                url = next['url'] if (next := resp.links.get('next')) else None
                print(url, len(users))
                pages += 1
                if pages == max_pages: break
    end = time.time()
    print(f'{end - start:5.1f}')

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

it runs in about 5 sec

here's a similar example using the Okta SDK:
```python
import okta.client
import asyncio
import time

max_pages = 10

async def main():
    client = okta.client.Client()
    start = time.time()
    pages = 0
    users, resp, err = await client.list_users()
    while users:
        print(len(users))
        users, err = await resp.next() if resp.has_next() else (None, None)
        pages += 1
        if pages == max_pages: break
    end = time.time()
    print(f'{end - start:5.1f}')

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

it runs in about 10 seconds.

we've seen similar performance differences using sync `requests` / `sessions` in Python and also in other languages and libraries.

**Comment by serhiibuniak-okta** [comment]
@gabrielsroka Thank you for providing a lot of details. I'll take a look at such improvement asap.

**Comment by serhiibuniak-okta** [comment]
@gabrielsroka I've added PR: https://github.com/okta/okta-sdk-python/pull/271
This really improves performance and doesn't introduce breaking changes. Is it convenient to create ClientSession outside?
You can find example under https://github.com/okta/okta-sdk-python/tree/add-reusable-session#other-configuration-options

**Comment by serhiibuniak-okta** [comment]
It's a bit hard to close session correctly, especially in async world. If we create session under the hood, when we should close it? When garbage collector starts, i.e. try to close session inside `__del__` method or use atexit. But both of these are sync by its nature and session is async, thus it multiply complexity of correct solution.

**Comment by gabrielsroka** [comment]
how about `__aexit__`. that's what aiohttp uses: https://github.com/aio-libs/aiohttp/blob/master/aiohttp/client.py#L1073-L1079

**Comment by serhiibuniak-okta** [comment]
Yes, `__aexit__` is being used within `async with` context, i.e. it is being called when we leave async context manager:

```py
import asyncio


class MySession:
    async def __aenter__(self):
        print('Starting session')
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        print('Closing session')


async def main():
    print('Before using session')
    async with MySession() as s:
        print('Inside session')
    print('After using session')


asyncio.run(main())
```

Output:
```
Before using session
Starting session
Inside session
Closing session
After using session
```

**Comment by gabrielsroka** [comment]
i don't see `__aexit__` in the SDK (except for a few tests). is it there? different branch maybe? do you have a url?

which README? aiohttp's?

maybe the solution is instead of doing
```python
client = OktaClient()
client.get...
```

do
```python
async with OktaClient() as client:
    client.get...
```
and using Okta's `__aexit__` to call aiohttp's `__aexit__`

also, https://docs.aiohttp.org/en/stable/client_quickstart.html says

> Note
Don’t create a session per request. Most likely you need a session per application which performs all requests altogether.
More complex cases may require a session per site, e.g. one for Github and other one for Facebook APIs. Anyway making a session for every request is a very bad idea.
A session contains a connection pool inside. Connection reusage and keep-alives (both are on by default) may speed up total performance.

**Comment by serhiibuniak-okta** [comment]
There is no __aexit__ in SDK, because it is defined for ClientSession object and will be executed automatically when we use `async with` construction.
So, with suggested solution we should do like the following:
```py
async with aiohttp.ClientSession() as session:
    client = OktaClient(session)
    client.get...
```

Regarding your option:
```
async with OktaClient() as client:
    client.get...
```
looks reasonable, I'll investigate if I can implement it in this way, so for backward compatibility we still can use it as it was before.

**Comment by gabrielsroka** [comment]
> for backward compatibility we still can use it as it was before

i understand backward compatibility is important, but it doesn't seem like a good idea to "use it as it was before" when the docs say "Don’t create a session per request". maybe it's only a performance consideration and some clients don't care about performance, but i'm guessing Okta's servers care about performance, and this is probably affecting them.

**Comment by serhiibuniak-okta** [comment]
@gabrielsroka Python SDK v2.4.0 has been released: https://github.com/okta/okta-sdk-python/releases/tag/v2.4.0 (you can find an example of usage here)
I'm closing this issue as resolved.
