### ISSUE TITLE
Support Yubikey

### ISSUE THREAD

**Issue by aaronlelevier** [okta/okta-sdk-python#268]
From the REST API documentation, I found this Yubikey [example](https://developer.okta.com/docs/reference/api/authn/#request-example-for-enroll-yubikey-factor).

I searched this repo, but did not find any matches for Yubikey support and would like to use Yubikey MFA. Is this a desired feature?

**Comment by arvindkrishnakumar-okta** [comment]
@bretterer Can you help with this one please?

**Comment by matayto** [comment]
Any updates on this?
