### ISSUE TITLE
What are the query parameters?

### ISSUE THREAD

**Issue by saloni-canva** [okta/okta-sdk-python#274]
This is a screenshot from the readme file. It says here to "Check the method definition for details on which query parameters are accepted"
![image](https://user-images.githubusercontent.com/90663513/153059970-f50fbd2c-48f3-4f6b-89f3-5641a53b8043.png)

On checking the method definition, I can see different types of ways of querying eg filter, limit etc. But I cannot see which parameters it is accepting. So far, I only know it is accepting status because of the above example. 
![image](https://user-images.githubusercontent.com/90663513/153060169-a7e25988-7879-4702-89f7-dd87cce728d6.png)

**Comment by arvindkrishnakumar-okta** [comment]
@saloni-canva Thanks for your post.

@bretterer can you please help take a look?

**Comment by serhiibuniak-okta** [comment]
Each API endpoint may have different set of query params. In this case, you deal with Users API, so you should refer to our docs https://developer.okta.com/docs/reference/api/users/#list-users-with-a-filter (you can find docs for any available API under https://developer.okta.com/docs/reference/core-okta-api/)

**Comment by saloni-canva** [comment]
Thank you! This is great
