### ISSUE TITLE
How to use the functions in an object oriented class? 

### ISSUE THREAD

**Issue by saloni-canva** [okta/okta-sdk-python#275]
I am trying to use the functions in a class like this: 
<img width="407" alt="image" src="https://user-images.githubusercontent.com/90663513/153068403-d9f6f193-2975-4cfa-9ee4-46d99d34ba5a.png">

However I am getting this error: 
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/90663513/153068369-a741d16a-a1cf-47a4-8ec9-a1222407daf7.png">

I am guessing it has to do with the ```asyncio``` library - can you suggest what to do?

**Comment by arvindkrishnakumar-okta** [comment]
@saloni-canva Thanks for your post.

@bretterer can you please help with this one?

**Comment by serhiibuniak-okta** [comment]
Yes, you're dealing with async approach and we have a lot of examples in our [README](https://github.com/okta/okta-sdk-python/blob/master/README.md)
IMHO, you should start from getting acquainted with [asyncio](https://docs.python.org/3/library/asyncio.html) to use our SDK in your project efficiently. In a nutshell, you need to use `await` on functions inside `async` functions. It doesn't break OOP, async is about concurrency.

**Comment by gabrielsroka** [comment]
@saloni-canva 
here's are 2 more complete examples. as @serhiibuniak-okta said above, you must always use `async def` and `await client...`. note that `def __init__` can't be `async`

without a class:
```python
import okta.client
import asyncio

async def main():
    async with okta.client.Client() as client:
        users, resp, err = await client.list_users()
        print(f'{users= }')
        print(f'{resp= }')
        print(f'{err= }')

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

with a class:
```python
import okta.client
import asyncio

async def main():
    ok = Okta()
    await ok.list_users()

class Okta:
    def __init__(self):
        self.client = okta.client.Client()

    async def list_users(self):
        users, resp, err = await self.client.list_users()
        print(f'{users= }')
        print(f'{resp= }')
        print(f'{err= }')


loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

**Comment by gabrielsroka** [comment]
It goes in the main file, not in the class file.

Why don't you give it a try, maybe in both places and see what works. If not you can upload small samples of your code and we can give it a try together.

**Comment by saloni-canva** [comment]
Sounds good, this worked for me: 


oktaclass.py: 
```
class Okta:
    def __init__(self):
        self.client = OktaClient(config)

    async def list_users(self):
        users, resp, err = await self.client.list_users()
        print(f'{users}')
        print(f'{resp}')
        print(f'{err}')
```


playground.py:
```
import crayons
import constants
import asyncio
from oktaclass import Okta

okta = Okta()

async def playground():
    await okta.list_users()

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(playground())

```

**Comment by serhiibuniak-okta** [comment]
@saloni-canva Happy to see this works for you. Then I close this issue as resolved. Feel free to reopen this issue or create a new one if your problem exists still. Thanks for using OKTA!
