### ISSUE TITLE
Certificate expired error with custom org url

### ISSUE THREAD

**Issue by JimJohnsonColgate** [okta/okta-sdk-python#282]
We have a custom url configured for our org, which previously has worked fine with the Okta API (custom url vs. original Okta url were interchangeable).

Recently we tested Okta-managed certificates (https://developer.okta.com/docs/guides/custom-url-domain/main/#configure-a-custom-domain-through-okta-managed-certificates) in our preview org. Now, the Okta python client is throwing a "Certificate Expired" error for the custom url, even though the certificate is not expired:

- user, resp, err = await oktaClient.get_user(ID)
- '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)'
- The certificate is valid from 02/23/22 to 05/24/2022
- I checked the full certificate chain for the custom url, and none of the other certificates are expired
- The certificate for our original url is also valid
- The original Okta url works normally

I'm not sure if this an Okta back end issue or an issue with this library, but I cannot replicate it using either Postman or the normal requests library, so it seems specific to the Okta SDK for python.

**Comment by JimJohnsonColgate** [comment]
Looks like this may be related to a recent LetsEncrypt certificate rotation: https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/

Potentially Okta is serving up an old certificate under certain circumstances?

**Comment by MasterSergius** [comment]
@JimJohnsonColgate it looks like this issue is specific to python, could you please try the following? https://stackoverflow.com/questions/63742983/certificate-verify-failed-certificate-has-expired-ssl-c-when-attempti/69550170#69550170

**Comment by JimJohnsonColgate** [comment]
Interesting. That worked. Thanks a lot.
