### ISSUE TITLE
The client_assertion JWT kid is invalid.

### ISSUE THREAD

**Issue by michaelmisshore** [okta/okta-sdk-python#289]
When configuring an OktaClient via privateKey, if the application you are targeting has multiple JWKs, the following error occurs:

`{'message': "HTTP 401 {'error': 'invalid_client', 'error_description': 'The client_assertion JWT kid is invalid.'}"}`

This works fine if the application only has one JWK. The issue is that the signed JWT does not contain the `kid`.

Potential fix: https://github.com/michaelmisshore/okta-sdk-python/commit/3e842efd3ec0cf23dd61cd89a61a404d6c8d0f47.

**Comment by bretterer** [comment]
Resolved in 2.9.0
