### ISSUE TITLE
Any plans for supporting typing?

### ISSUE THREAD

**Issue by Fruglemonkey** [okta/okta-sdk-python#295]
Hi, are there any plans for this SDK to provide types or stubs for those of us that use types in python (IE with mypy or pyright)?

Not a breaking issue, but I find when working with this library ~50-60% of my PRs are just generating stub files 😓

**Comment by aarongranick-okta** [comment]
@Fruglemonkey Thanks for the question! I will find someone from our backend SDK team who can answer it for you.

**Comment by bretterer** [comment]
@Fruglemonkey Thank you for the suggestion here.  I can not comment on adding these to our library at the moment, but I will discuss this internally.

Internal Ref: OKTA-487505

**Comment by Fruglemonkey** [comment]
👀  Any update on the internal ref?

**Comment by bretterer** [comment]
At this point in time, We will not be supporting typing.  I apologize for any inconveniences this may cause you. If this is something that is absolutely necessary to your development, please reach out to Okta support.
