### ISSUE TITLE
deprecation warning when using asyncio

### ISSUE THREAD

**Issue by fawaf** [okta/okta-sdk-python#297]
when running with the examples given in the readme, a`DeprecationWarning: There is no current event loop` warning is thrown.

```
...snip...
loop = asyncio.get_event_loop()
loop.run_until_complete(do_stuff())
...snip...
```

using python 3
```
% python --version
Python 3.10.4
```

**Comment by Interperle** [comment]
This Warning occurs if you didn't use an event_loop before. Just use:

...snip...
loop = asyncio.new_event_loop()
loop.run_until_complete(do_stuff())
...snip...

When using it the first time.

**Comment by fawaf** [comment]
ahh, the readme doesn't really make that clear.

**Comment by sacedo-asapp** [comment]
You can also replace this:
loop = asyncio.get_event_loop()
loop.run_until_complete(main())

With this:
asyncio.run(main())

Works for Python >3.10

**Comment by gabrielsroka** [comment]
@Interperle i think @sacedo-asapp 's solution is the more "correct", based on reading https://docs.python.org/3.10/library/asyncio-eventloop.html#asyncio.get_event_loop

@fawaf the readme was written before Python deprecated it. the docs need to be updated:

```python
asyncio.run(main())
```

note, your mileage may vary depending on which OS and version of Python you're running.
