### ISSUE TITLE
`urn:ietf:params:oauth:grant-type:saml2-bearer` Not included in OAuthGrantType

### ISSUE THREAD

**Issue by bfrisbie-brex** [okta/okta-sdk-python#298]
Using Postman, I can create an OAuth2 Client with `urn:ietf:params:oauth:grant-type:saml2-bearer` as one of the `grant_types`.

However, that is missing from [OAuthGrantType here](https://github.com/okta/okta-sdk-python/blob/46184663baccb926dc14ab964dfd9406d375de0a/okta/models/o_auth_grant_type.py#L24-L36 ), and thus I can't create such an OAuth2 Client using the Python SDK.

**Comment by bfrisbie-brex** [comment]
Hi @laura-rodriguez , I'm sorry for not responding sooner, I overlooked your response.

Yes, this issue is blocking my team from migrating from our existing OAuth Server to Okta's API Access Management solution.

Do you think your team might be able to address this issue within the next several weeks?

**Comment by bfrisbie-brex** [comment]
Hi @laura-rodriguez , checking in on this again: Do you think your team might be able to address this issue within the next several weeks?

**Comment by laura-rodriguez** [comment]
Hey @bfrisbie-brex,

Just to get you unblocked while I get a response from the team, you can consider making the request manually using the SDK as explained [here](https://github.com/okta/okta-sdk-python#call-other-api-endpoints).

Let me know if this workaround works for you in the meantime.

**Comment by bfrisbie-brex** [comment]
Hi @laura-rodriguez , yes, that has been our plan from the beginning.

The reason I asked if the Okta team is able to address this issue in the next few weeks is to determine if we should directly request the API directly as a "workaround" for this bug in the python SDK, or if we can expect this bug to be fixed sooner rather than later.

**Comment by laura-rodriguez** [comment]
Hey @bfrisbie-brex ,
I understand this is a low-priority bug since there's a workaround, so I suggest you keep making the manual request in the meantime.

**Comment by bfrisbie-brex** [comment]
@laura-rodriguez to be clear, we haven't written any code to make the manual request yet, in the hopes Okta will fix its bugs in a timely manner.

It would be nice if Okta could provide a time estimate on when this bug will be addressed.

**Comment by bfrisbie-brex** [comment]
Hi @laura-rodriguez , this bug is becoming higher priority for our team, as we a python script to migrate dozens of OAuth Clients over to Okta, and calling the API individually for each client is not practical.

Is there anything the priority of this issue/request can be increased?

On the surface, it doesn't _seem_ like it should take a massive engineering effort to fix.

**Comment by laura-rodriguez** [comment]
Hey @bfrisbie-brex,
I truly apologize for the inconvenience. We are experiencing some challenges in addressing Python Github issues. Please bear with us while we work to improve this process and SDK by addressing your feedback.
