### ISSUE TITLE
`token_endpoint_auth_method` = `none` raises an Api validation Error

### ISSUE THREAD

**Issue by bfrisbie-brex** [okta/okta-sdk-python#299]
When I try to create an OAuth Client with the Python SDK, where `token_endpoint_auth_method` is set to `none`, I get back:

> Okta HTTP 400 E0000001 Api validation failed: token_endpoint_auth_method\ntoken_endpoint_auth_method: 'token_endpoint_auth_method' is invalid. Valid values: [client_secret_basic, client_secret_post, client_secret_jwt, private_key_jwt].

The error shouldn't occur, as `none` is defined as an acceptable value for `token_endpoint_auth_method` in the RFC: https://datatracker.ietf.org/doc/html/rfc7591

I don't seem to encounter the same problem when using Postman.

**Comment by justinabrokwah-okta** [comment]
Hey @bfrisbie-brex , what type of app are you trying to set the `token_endpoint_auth_method` in?

**Comment by bretterer** [comment]
Resolved in 2.9.0
