### ISSUE TITLE
Set xml_attribs=True in OktaApiResponse.build_xml_response 

### ISSUE THREAD

**Issue by molar-volume** [okta/okta-sdk-python#302]
**Problem description:**
GET on `/api/v1/apps/${applicationId}/sso/saml/metadata` returns `xml` with important content in attributes, but method `build_xml_response` leaves attributes out.

**Proposed solution:**
https://github.com/okta/okta-sdk-python/blob/master/okta/api_response.py#L97
```python
        self._body = xmltodict.parse(response_body, xml_attribs=True)
```

**Comment by bretterer** [comment]
Resolved in 2.9.0
