### ISSUE TITLE
Implement ApplicationClient.get_metadata_for_saml_application

### ISSUE THREAD

**Issue by molar-volume** [okta/okta-sdk-python#303]
While you can create SAML app using `ApplicationClient.create_application`, there is no method to retrieve it's metadata to complete the setup on 3rd party platform, e.g. Snowflake.

The method should retrieve metadata from endpoint `/api/v1/apps/${applicationId}/sso/saml/metadata`.
This requires fix of https://github.com/okta/okta-sdk-python/issues/301 and https://github.com/okta/okta-sdk-python/issues/302, related to handling XML response.

**Comment by bretterer** [comment]
Resolved in 2.9.0
