### ISSUE TITLE
BUG: flatdict installation fails on python 3.7.1

### ISSUE THREAD

**Issue by molar-volume** [okta/okta-sdk-python#305]
**Current behavior**
If python 3.7 is specified in Travis config, version 3.7.1 is used, which causes error on `flatdict` installation:
```
Collecting flatdict
  Downloading flatdict-4.0.1.tar.gz (8.3 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
```

**Propose solution**
Travis should use higher patch version (e.g. 3.7.13), and installation will pass fine.
```

**Comment by bretterer** [comment]
Resolved in 2.9.0
