### ISSUE TITLE
OktaClient.create_application_group_assignment method fail due to wrong headers usage

### ISSUE THREAD

**Issue by RomainMichau** [okta/okta-sdk-python#309]
When using the method
```python
self.__okta_client.create_application_group_assignment(app_id, group_to_assign, {})
```
I got an error message: 
`{'errorCode': 'E0000021', 'errorSummary': 'Bad request.  Accept and/or Content-Type headers likely do not match supported values.', 'errorLink': 'E0000021', 'errorId': 'oaeW2vyTfU-RUOQoDiQkX1NPQ', 'errorCauses': []}`

I noticed that when sending the request to okta API the okta python sdk is using the header ''Content-Type: application/x-www-form-urlencoded" while okta expect ''Content-Type: application/json"  (see the API [doc](https://developer.okta.com/docs/reference/api/apps/#assign-group-to-application))

I guess that this issue is related to #301

**Comment by bretterer** [comment]
Resolved in 2.9.0
