### ISSUE TITLE
Error retrieving SAML properties from `get_application` call

### ISSUE THREAD

**Issue by enfont** [okta/okta-sdk-python#312]
**Describe the bug**

In our Okta environment we have defined a Datadog Application with SAML2.0 login enabled.

When getting the properties for an existing instance for a Datadog application from the UI or Postman we are getting properly the "settings" field for the application:

```
    "settings": {
        "app": {
            "environment": "com",
            "companyId": "/id/TEST"
        },
        "notifications": {
            "vpn": {
                "network": {
                    "connection": "DISABLED"
                },
                "message": null,
                "helpUrl": null
            }
        },
        "notes": {
            "admin": null,
            "enduser": null
        },
        "signOn": {
            "defaultRelayState": null,
            "ssoAcsUrlOverride": null,
            "audienceOverride": null,
            "recipientOverride": null,
            "destinationOverride": null,
            "attributeStatements": []
        }
    },...
```

but when calling the SDK get_application with the same application id we are getting this kind of results. settings/app come empty, and SignOn seems to be completely different

```
'settings': {
  'app': {}, 
  'notes': {}, 
  'notifications': {
    'vpn': {
      'network': {'connection': 'DISABLED', 'exclude': [], 'include': []}}}, 
  'signOn': {
    'acsEndpoints': [], 
    'attributeStatements': [], 
    'inlineHooks': []
  }
}

```

**To Reproduce**

Most important thing is having in your organization a Datadog app with SAML2.0 activated, and then create a new instance of this application. 

Then just call the get_application call to see the weird behaviour. We provide a quick & dirty code to reproduce the issue

```
import asyncio
from okta.client import Client as OktaClient
from okta.http_client import HTTPClient as OktaHTTPClient

class OktaAdapter:

    def __init__(self, url: str, token: str):
        self.__token = token
        self.__url_base = url.strip('/')

        org_url = self.__url_base.split('.okta.com')[0]
        org_url = org_url.split('-admin')[0] + '.okta.com'
        config = {'httpClient': OktaHTTPClient,
                  'orgUrl': org_url,
                  'raiseException': True,
                  'token': self.__token}
        self._okta_sdk = OktaClient(config)

    async def get_app_by_id(self, app_id):
        result, _, _ = await self._okta_sdk.get_application(app_id)
        return result.as_dict()


okta_api_url = "https://mpi-internal-test-admin.okta.com"
okta_api_token = "API_TOKEN"
oktaadapter = OktaAdapter(okta_api_url, okta_api_token)

app = asyncio.run(oktaadapter.get_app_by_id("APP_ID"))
print (f'Get Application:\n{app}\n')
```

**Expected behaviour**

Return the proper settings for both app and signOn fields. 

**Full Stack Trace**

No stack trace returned

**Environment and Versions:**

- Both Mac and Linux
- Python version 3.8.5
- Tested same behaviour with both okta 2.3 and 2.6.0

**Additional context**

From our investigations, the problem seems to be in the call done after getting the proper body from the API

https://github.com/okta/okta-sdk-python/blob/master/okta/resource_clients/application_client.py#L240

After this line the properties are messed up

**Comment by enfont** [comment]
Good morning

As far as we have seen after further investigation, the issue seems to be here:

https://github.com/okta/okta-sdk-python/blob/b0788d37c3f007ca43a15a11aab0128226422c97/okta/models/application_settings_application.py#L37

Once the Application Settings are requested, the "app" settings returned are completely empty.

As far as we can see, this is defined like this in the ApplicationSettingsApplication API SPEC definition, which is blank

https://github.com/okta/okta-management-openapi-spec/blob/master/resources/spec.yaml#L9681

Can you please take a look?

Thanks in advance

**Comment by bryanapellanes-okta** [comment]
@enfont  Thank you for your patience as we review the issue.  See the updated branch here:
https://github.com/okta/okta-sdk-python/tree/OKTA-588345-regen-applicationsettingsapplication

Please test that the changes therein correct the issue you are seeing.  Once confirmed I will move forward to merge the changes.
