### ISSUE TITLE
Inconsistent return types from similar methods

### ISSUE THREAD

**Issue by fionn** [okta/okta-sdk-python#322]
Some return types differ unexpectedly.

For instance, `GroupClient.remove_user_from_group` has return type `tuple[OktaAPIResponse, Exception]`, but `GroupClient.list_group_users` has return type `tuple[<result>, OktaAPIResponse, Exception]`.

It is understandable that some non-`GET` methods don't return a result, but in that case it would be much nicer to have a response of a 3-tuple with the result `None` as the first element.

Even better would be something like `namedtuple("APIReturn", ["result", "response", "error"])`.

One specific case where this would be helpful is in function wrappers. Consider e.g.
```python
def sync_result(f: Coroutine[None, None, tuple[T, Any, Any]]) -> T:
    return asyncio.run(f)[0]
```
which will misbehave when invoked on methods that don't have a result.

**Comment by bretterer** [comment]
I appreciate your feedback, but at this time, we are not able to update our return types for this request. If this is a development stopping issue for you, please do reach out to Okta support.
