### ISSUE TITLE
`get_application_user_schema()`camel cases attribute names containing `_`

### ISSUE THREAD

**Issue by exitcode0** [okta/okta-sdk-python#325]
when calling `get_application_user_schema()` for an application with a custom attribute `test_attribute`
(display name - `test attribute` variable name - `test_attribute`)
the name is malformed to camel case
```python
schema, resp, err = await okta_client.get_application_user_schema(appInstanceId=args.app_id)
print(schema.definitions.custom.properties)
```
returns the following
```json
{"testAttribute": {"title": "test attribute", "type": "string", "scope": "NONE", "master": {"type": "PROFILE_MASTER"}, "sensitive": False}}
```

my limited investigation of this seems to point towards `get_application_user_schema()` calling `form_response_body()`
which calls `camel_case()` on keys

**Comment by bretterer** [comment]
This should be resolved in 2.9.0.  If it is still an issue, please open a new issue and reference this one
