### ISSUE TITLE
Add device_client to resource_clients

### ISSUE THREAD

**Issue by sacedo-asapp** [okta/okta-sdk-python#326]
Hi! Is there plans to add a module to manage devices? 

I'd like to take advantage of this SDK mainly to pull data from registered devices, the API endpoint exist `/api/v1/devices` so it is a matter of adding the necessary functions to interact with it. I'm not sure how to request for this but apparently this SDK has  autogenerated files so I'm guessing it is not just a thing I can create and send a PR to you.

**Comment by gabrielsroka** [comment]
you can call arbitrary endpoints:
https://github.com/okta/okta-sdk-python/#call-other-api-endpoints

here's some sample code, with pagination
```python
# `async with` reuses the session, so it's is much faster.
async with Client() as client:
    req, _ = await client.get_request_executor().create_request('get', '/api/v1/devices')
    resp, _ = await client.get_request_executor().execute(req)
    devices = resp.get_body()
    while devices:
        for device in devices:
            print(device['id'], device)
        devices, _ = await resp.next() if resp.has_next() else (None, None)
```

if u wanna get fancier, here's a subclass
```python
class Client(okta.client.Client):
    """A thin wrapper around the Okta SDK."""

    async def get_devices(self):
        req, _ = await self.get_request_executor().create_request('get', '/api/v1/devices')
        resp, _ = await self.get_request_executor().execute(req)
        devices = resp.get_body()
        while devices:
            for device in devices:
                yield device
            devices, _ = await resp.next() if resp.has_next() else (None, None)
```

and a way to call it
```python
# `async with` reuses the session, so it's is much faster.
async with Client() as client:
    async for device in client.get_devices():
        print(device['id'], device)
```

**Comment by bretterer** [comment]
At the current time, we are not able to add this endpoint to the Python SDK.  As @gabrielsroka mentioned, this is the best workaround for you.
