### ISSUE TITLE
When is the next release - important necessary changes 

### ISSUE THREAD

**Issue by almogca** [okta/okta-sdk-python#335]
Receiving `ValueError` with the following message:
'interaction_code' is not a valid OAuthGrantType

Problem is solved in current version of the file `okta/models/o_auth_grant_type.py`, where you added newer values of this enum, but it's still not part of any release. Can you add it, even to a minor version? :)

Thank you!

**Comment by bretterer** [comment]
2.9.0 has been released with a lot of updates.
