### ISSUE TITLE
application client - support credentials/secrets

### ISSUE THREAD

**Issue by exitcode0** [okta/okta-sdk-python#336]
The following endpoint doesn't appear to be supported by the SDK
thinking that this might be an intentional choice, wanting to confirm
`/api/v1/apps/${applicationId}/credentials/secrets`

**Comment by bretterer** [comment]
This endpoint is not one we cover in our SDK's.  You can always use https://github.com/okta/okta-sdk-python/#call-other-api-endpoints to call an arbitrary endpoint.
