### ISSUE TITLE
No new release since Oct 2015

### ISSUE THREAD

**Issue by ksshetty** [okta/okta-sdk-python#34]
There has not been a new release since the initial release in Oct 2015. Is the expectation that we need to clone the source code regularly or can we expect to have released versions in the future?

**Comment by ksshetty** [comment]
It would be great if someone could kindly comment on this issue. Thanks in advance.

**Comment by jmelberg-okta** [comment]
@ksshetty: We are making a few more updates to this SDK before an official `1.0` release to `pypi`. We apologize for the inconvenience and will publish an update as soon as we can.

**Comment by ksshetty** [comment]
@jmelberg-okta Thanks for the response. Is there a ballpark estimate as to when the 1.0 release is expected to be out?

**Comment by jmelberg-okta** [comment]
@ksshetty: We will be pushing a minor update to `pypi` within the next couple of weeks.

Thanks for your patience!

**Comment by jmmercadom** [comment]
Hi @jmelberg-okta

A suggestion: you could start using [Milestones](https://help.github.com/articles/about-milestones/) and [Releases](https://help.github.com/articles/creating-releases/) features from GitHub to give visibility of next releases and it's milestones.

Regards!

**Comment by nicolastrres** [comment]
Hi @jmelberg-okta do you know when you will be pushing a new version to pypi?

**Comment by 007** [comment]
@jmelberg-okta ping again, is #45 the intended 0.1.x release gate? It'd be nice to get 0.0.4 to pypi while that's in process, just the bugfixes without the massive restructuring and cleanup.

**Comment by edpark** [comment]
+1

**Comment by jmelberg-okta** [comment]
All - Sorry for the long wait! Just released 0.0.4 to [pypi](https://pypi.python.org/pypi/okta/0.0.4). 

@007: Yes, #45 is in the early stages of development and intended to be a 0.1.x release.
