### ISSUE TITLE
Support ResourceSet - api/v1/iam/resource-sets

### ISSUE THREAD

**Issue by exitcode0** [okta/okta-sdk-python#340]
the `api/v1/iam/resource-sets` API is a part of the [Okta open API spec](https://github.com/okta/okta-management-openapi-spec/blob/master/resources/3.0/management.yaml#L221-L223) but has yet to be implemented into this SDK

**Comment by gabrielsroka** [comment]
some code u can run on your own (https://github.com/okta/okta-sdk-python/#call-other-api-endpoints)

```python
import okta.client
import asyncio

async def main():
    # `async with` reuses the session, so it's much faster.
    async with Client() as client:
        async for resource_set in client.list_resource_sets():
            print(resource_set['label'])

class Client(okta.client.Client):
    """A thin wrapper around the Okta SDK."""

    async def list_resource_sets(self):
        # see https://developer.okta.com/docs/reference/api/roles
        async for resource_set in self.get_iam_objects('/api/v1/iam/resource-sets', 'resource-sets'):
            yield resource_set
    
    async def get_iam_objects(self, url, key):
        # see https://github.com/okta/okta-sdk-python/#call-other-api-endpoints
        while url:
            exec = self.get_request_executor()
            req, _ = await exec.create_request('get', url)
            resp, _ = await exec.execute(req)
            page = resp.get_body()
            for obj in page[key]:
                yield obj
            url = page.get('_links', {}).get('next', {}).get('href')
            
asyncio.run(main())
```

**Comment by bretterer** [comment]
This endpoint was introduced in our Open API Spec v3.  Currently, there are no plans to upgrade Python SDK to v3. 

You can however use a tool such as openapi-generator.tech (our recommended OASv3 generator tooling) to build a custom SDK in Python.

**Comment by exitcode0** [comment]
Hey @bretterer.

> there are no plans to upgrade Python SDK to v3.

Any chance you can expand upon this?

Is this limited to the Python SDK or are all Okta SDKs not planning to support the Open API Spec v3?
Was the Open API Spec v3 not intended for use with the SDks?

Having this API available natively is more of a want rather than a need for me
That said, If the Open API Spec v3 will be supported in other SDKs, i'm happy to switch to using another 😄

**Comment by bretterer** [comment]
@exitcode0 currently, we have migrated our .NET, Java, and Golang SDK's to OASv3.  As I mentioned, we do not have current plans to upgrade Python to this version.

We will be opening up the v3 spec into NPM in the future to allow for developers to build their own SDK with our spec.  We recommend  using openapi-generator.tech for doing this as this is the platform we use for our other languages.

**Comment by gabrielsroka** [comment]
https://github.com/okta/okta-sdk-python/issues/375
