### ISSUE TITLE
Error importing Client in 2.9+

### ISSUE THREAD

**Issue by harry-uglow** [okta/okta-sdk-python#350]
When importing the Client we're encountering the following error now that we're using version 2.9.1:
```
Traceback:
pipelines/okta/tasks.py:9: in <module>
    from okta.client import Client as OktaClient
venv/lib/python3.9/site-packages/okta/client.py:25: in <module>
    from okta.request_executor import RequestExecutor
venv/lib/python3.9/site-packages/okta/request_executor.py:4: in <module>
    from okta.oauth import OAuth
venv/lib/python3.9/site-packages/okta/oauth.py:2: in <module>
    from okta.jwt import JWT
venv/lib/python3.9/site-packages/okta/jwt.py:2: in <module>
    from Cryptodome.PublicKey import RSA
E   ModuleNotFoundError: No module named 'Cryptodome'
```

This is reproducible in a fresh Python client simply by running `from okta.client import Client`.

At the moment we've fixed this by locking our dependency to 2.8.x - any help in resolving this would be appreciated.

**Comment by harry-uglow** [comment]
Hi, thanks for the response. Yes, worth noting that this happens on our CI runner as well which installs all its packages from scratch.
From: ***@***.***
Sent: 14 March 2023 17:42
To: ***@***.***
Reply to: ***@***.***
Cc: ***@***.***; ***@***.***
Subject: Re: [okta/okta-sdk-python] Error importing Client in 2.9+ (Issue #350)


Hey @harry-uglow<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fharry-uglow&data=05%7C01%7C%7C0cd1f0583e364511458008db24b36d98%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638144125268852148%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tY%2BRPxR7svmmSWpa%2BosR5tkAzbwZ6zqs6Ul1tgrrBhg%3D&reserved=0>, is just running the 1 line causing the error?
Have you tried uninstalling and reinstalling the package completely?

**Comment by fernandoreyez** [comment]
can confirm this is an issue with latest release

**Comment by fer-roz-d** [comment]
Hi, we also have this issue. 

The problem seems to be with https://github.com/okta/okta-sdk-python/pull/345

The new package is missing in setup.py

**Comment by justinabrokwah-okta** [comment]
Thanks for the inputs @harry-uglow , @fernandoreyez , @fer-roz-d 

Great catch @fer-roz-d , I'll create a PR to add it in there as well
