### ISSUE TITLE
Listing factors fails if a `signed_nonce` factor is encountered

### ISSUE THREAD

**Issue by SpencerLN** [okta/okta-sdk-python#360]
The [API docs](https://developer.okta.com/docs/reference/api/authenticators-admin/#authenticator-method-properties) specify that a `signed_nonce` is a valid type of factor, but the Python SDK is unable to return successfully if one is encountered and returns a `KeyError('signed_nonce')`:
<img width="316" alt="image" src="https://user-images.githubusercontent.com/6659148/236316918-b7a60961-383f-40ba-a1ad-1506631e1fa5.png">

```
    user_factors, user_factors_resp, user_factors_err = await okta_client.list_factors(
        user["_source"]["okta"]["id"]
    )
```

**Comment by cizo2000** [comment]
I have same behavior.

**Comment by wezham** [comment]
I experience the same

**Comment by eliavlivneh** [comment]
I experience the same behavior.
It seems that support for the `signed_nonce` factor hasn't been implemented in the Python SDK since being added to Okta - the `OKTA_FACTOR_TYPE_TO_FACTOR` dictionary in `constants.py` doesn't have the `signed_nonce` factor entry, and there is no corresponding model implemented under the `models` directory.

**Comment by cizo2000** [comment]
Yes, you can do it, but it's not proper solution if it's possible to fix openapi specs and refresh SDK to have all current types of factors covered. I am using it on 20+ servers.

**Comment by alfredkzr** [comment]
Same issue here with listing signed_nonce. Hope it can be fixed soon as I would prefer to use the SDK instead of workaround.

**Comment by gili-linx** [comment]
This is still happening in the latest version - 2.9.5. `OKTA_FACTOR_TYPE_TO_FACTOR` is missing the `SIGNED_NONCE` factor type. Can you please generate a new version of the SDK with this small fix?
