### ISSUE TITLE
HTTP/400 Errors if the API Token contains a newline

### ISSUE THREAD

**Issue by pduldig-at-tw** [okta/okta-sdk-python#44]
Ran into an issue where I am decrypting an [AWS encrypted] Okta API token that ended with a newline.
Normally, you would not include a newline on the token, but because of the tools I was using it inserted an extra \n. It was non-obvious as the inputs to my app were encrypted. 
Some deeper urllib3 debug logging helped

When requests module constructed the POST, it contained the SSWS token value with the extra \n, which is not a valid HTTP request. 
The Apache front end webserver at okta rejects the malformed request, and returns some standard apache HTML error page.
The okta-sdk library never expects HTML payloads in the response, and throws a JSON parsing exception.

(The request is not reaching the Okta application servers where JSON can be returned in the response. It is being dropped as a HTTP/400 by the Apache service fronting the application servers).

For defensiveness, I am suggesting the module handles non-HTML responses gracefully, and/or strips any whitespace/newlines from the user specified token.

I have since reencrypted the token without the extra newline, and everything works, but in case someone else has this problem the module could handle this edge case.

**Comment by bretterer** [comment]
I am going to close this Issue as stale. We have recently released a 1.x version of this SDK and believe this is now resolved.

If you find that you are still having an issue, please let us know if you are still having this issue.
