### ISSUE TITLE
The request body is not well-formed during User update

### ISSUE THREAD

**Issue by steveYeah** [okta/okta-sdk-python#49]
When reading a user from the API, altering some of the details on the profile, and then updating details via the API I see the following error
```
okta.framework.OktaError.OktaError: The request body was not well-formed`
```

Code:
```
try:
    # Okta returns [] if not found
    okta_users = users_client.get_users(
        query=supplier_details['email']
    )
except OktaError as okta_error:
    raise OktaCommsError(str(okta_error))

okta_user = okta_users[0]
okta_user.profile.email = supplier_details['email']
okta_user.profile.firstName = supplier_details['first_name']
okta_user.profile.lastName = supplier_details['last_name']
okta_user.profile.login = supplier_details['login']
okta_user.profile.displayName = supplier_details['display_name']
okta_user.profile.primaryPhone = supplier_details['primary_phone']
okta_user.profile.city = supplier_details['city']

try:
    users_client.update_user(okta_user)
except OktaError as okta_error:  # Error raises here
    # Something failed in the update
    raise OktaCommsError(str(okta_error))
```

Is there something I'm missing here?

**Comment by steveYeah** [comment]
I had some time today and had a look into this error and found the cause.

When fetching the data from Okta, altering it and then sending it back, the serialiser places the `_links` data into `links` and not `_links`. When that is then serialised back into json, the user model contains a `links` attribute, which causes the error

To get around this you can move the data to _links
```
okta_user._links = deepcopy(okta_user.links)
okta_user.links = None
```
I think this should be handled during serialisation to avoid this error

**Comment by bretterer** [comment]
We have recently released a 1.x version of this SDK and all api calls and setup is different. Please check out our new version on PyPi.

If you find that you are still having an issue, please let us know if you are still having this issue.
