### ISSUE TITLE
python3 support?

### ISSUE THREAD

**Issue by directionless** [okta/okta-sdk-python#50]
I'm starting to play with the API. Python 3 doesn't like the relative imports in https://github.com/okta/okta-sdk-python/blob/master/okta/__init__.py

Any plans of python3 support?

**Comment by bretterer** [comment]
@directionless I know this issue is over 3 years old, but we have just revived this SDK and updated it to have python3 support. Check out our latest release in the 1.x series from pypi and let us know what you think.
