### ISSUE TITLE
User update obliterates all other profile attributes not provided in the user model

### ISSUE THREAD

**Issue by heineman-bob** [okta/okta-sdk-python#51]
When updating a users profile the [UsersClient uses a put method](https://github.com/okta/okta-sdk-python/blob/master/okta/UsersClient.py#L75) instead of a post method which if you read the [rest documentation](https://developer.okta.com/docs/api/resources/users.html#update-user) completely overruns all other attributes in the profile if they are not provided in the request.   Since the user model only provides the ability for a partial update it should use the post method instead.

**Comment by bretterer** [comment]
We have recently released a 1.x version of this SDK and all api calls and setup is different which should resolve this issue. Please check out our new version on PyPi.

If you find that you are still having an issue, please let us know if you are still having this issue.
