### ISSUE TITLE
Cannot use Auth API for authentication only

### ISSUE THREAD

**Issue by bmacauley** [okta/okta-sdk-python#52]
I want to use the Okta Auth API for authentication only(ie no API key) for a CLI tool.

I cannot do this because an API key is required in the APIClient
okta-sdk-python/okta/AuthClient.py
okta-sdk-python/okta/framework/ApiClient.py

The documentation states this is not a requirement...
https://developer.okta.com/docs/api/resources/authn.html

**Comment by bmacauley** [comment]
#57 a fix for the issue

**Comment by heaje** [comment]
This is quite a bit late to the party, but simply passing in ' ' to the constructor for the API key will make it work fine for just authentication.

**Comment by bretterer** [comment]
@bmacauley We have fully updated our python library. As this library is meant to be managing resources only, we do require some sort of token to be provided. Our Management SDK (okta-sdk-python) does not handle any kind of authentication.
We do not currently have an authn library for python, but it is on our roadmap to have some sort of library for this in the future.
