### ISSUE TITLE
Cannot pass required fields for u2f

### ISSUE THREAD

**Issue by chrisleck** [okta/okta-sdk-python#53]
The Okta docs call for two fields to be passed in the signed assertion phase of U2F authentication: https://developer.okta.com/docs/api/resources/authn.html#post-the-signed-assertion-to-okta-to-complete-verification

However, the current python API doesn't allow those fields to be passed through: https://github.com/okta/okta-sdk-python/blob/master/okta/AuthClient.py#L44

**Comment by bretterer** [comment]
We have recently released a 1.x version of this SDK and all api calls and setup is different which should resolve this issue. Please check out our new version on PyPi.

If you find that you are still having an issue, please let us know if you are still having this issue.
