### ISSUE TITLE
sample to create a new App

### ISSUE THREAD

**Issue by sdementen** [okta/okta-sdk-python#54]
I am trying to create a new app through the `create_app_instance` method but without success.

The configuration of the AppInstance is not obvious.
```python
app_client = AppInstanceClient("...","...")
app = AppInstance()
app.label = "my-new-app"
app.signOnMode = "OPENID_CONNECT"
app_client.create_app_instance(app)
```
gets me a
`okta.framework.OktaError.OktaError: Internal Server Error`

If I also set credentials, visibility, settings and accessibility (by just using values from an existing app I get a 
`okta.framework.OktaError.OktaError: Api validation failed: mediated`

Could you post some simple sample to create an App ?

**Comment by mchurichi** [comment]
is this AppInstanceClient class really intended for App creation?

**Comment by bretterer** [comment]
We have recently released a 1.x version of this SDK and all api calls and setup is different which should resolve this issue. Please check out our new version on PyPi.

For creating an application, you can do the following:
```py
# Create SWA Application model and SWA Application in Okta
swa_app_settings_app = models.SwaApplicationSettingsApplication({
    'buttonField': 'btn-login',
    'passwordField': 'txt-box-password',
    'usernameField': 'txt-box-username',
    'url': 'https://example.com/login.html',
    'loginUrlRegex': '^https://example.com/login.html$'
})

swa_app_settings = models.SwaApplicationSettings({
    'app': swa_app_settings_app
})

swa_app_model = models.SwaApplication({
    'label': 'SWA Test App',
    'settings': swa_app_settings,
})

app, resp, err = await client.create_application(swa_app_model)
```

If you find that you are still having an issue, please let us know if you are still having this issue.
