### ISSUE TITLE
Auth2.0/OIDC support?

### ISSUE THREAD

**Issue by bmacauley** [okta/okta-sdk-python#58]
There is no support for the Okta Oauth2 and OIDC API's
https://developer.okta.com/docs/api/resources/oauth2.html
https://developer.okta.com/docs/api/resources/oidc.html

**Comment by bretterer** [comment]
@bmacauley This SDK specifically is only for management calls. The use cases for this can be found at https://developer.okta.com/docs/reference/ under the `Manage Okta Resources` heading.

We do not currently have an OIDC library specifically for Python, but it is on the roadmap to support in the future.

**Comment by achantavy** [comment]
Hi @bretterer, are you able to share or link to the roadmap? Around when do you expect OIDC support to be library-ized?

**Comment by robertjd** [comment]
If the original request is "how to use oauth to authenticate with the management APIs"? If so, then the link in the last comment is where you want to look.
