### ISSUE TITLE
Request body not well formed during verify

### ISSUE THREAD

**Issue by mikesiegel** [okta/okta-sdk-python#66]
Hello,

I'm trying to prompt the user for push auth via the SDK for testing purposes. According to the [documentation](https://developer.okta.com/docs/sdk/core/python_api_sdk/api/clients/FactorsClient.html#okta.FactorsClient.verify_factor) this is a valid request :

` factor_response = factorClient.verify_factor(user.id, factor.id)`

This results in the following call"

```
curl -i -s -k  -X $'POST' \
    -H $'User-Agent: python-requests/2.18.4' -H $'Content-Type: application/json' -H $'Authorization: SSWS XXXXXX' \
    --data-binary $'{\"activationToken\":null,\"answer\":null,\"passCode\":null,\"nextPassCode\":null}' \
    $'https://example.oktapreview.com/api/v1/users/XXXXX/factors/XXXXX/verify'
```

Which returns an error `The request body was not well-formed.`

  Fiddling around w/ Postman, submitting no body at all gives the desired results.

**Comment by gabrielsroka** [comment]
i got the same error. my "workaround" is to patch FactorsClient.verify_factor. change
https://github.com/okta/okta-sdk-python/blob/master/okta/FactorsClient.py#L153-L158
```python
        request = {
            'activationToken': activation_token,
            'answer': answer,
            'passCode': passcode,
            'nextPassCode': next_passcode
        }
```

to

```python
        request = {
            # 'activationToken': activation_token,
            # 'answer': answer,
            'passCode': passcode,
            # 'nextPassCode': next_passcode
        }
```

this works ok (ymmv, depending on which arguments you use).

another solution (which might break other things) is to add this to the Serializer class
https://github.com/okta/okta-sdk-python/blob/master/okta/framework/Serializer.py
```python
    def encode(self, obj):
        return JSONEncoder.encode(self, Utils.remove_nulls(obj))
```

it will remove the nulls

**Comment by bretterer** [comment]
We have recently released a 1.x version of this SDK and all api calls and setup is different which should resolve this issue. Please check out our new version on PyPi.

I believe the new update fixes this issue as we have completely redone the SDK and the way API calls are created.

If you find that you are still having an issue, please let us know if you are still having this issue.
