### ISSUE TITLE
Security status and support

### ISSUE THREAD

**Issue by hakube** [okta/okta-sdk-python#71]
Hi, is there any chance for Okta to support this library again? I managed to get this working on my Flask application and it's working well.

Is it secure enough for corporate use?

Thanks!

**Comment by rdegges** [comment]
Ping @nbarbettini @robertjd who help make these decisions.

**Comment by nbarbettini** [comment]
Hi @hakube, we don't have near-term plans to start supporting this library, sorry. I am not aware of any security vulnerabilities, but as with any external dependencies you should do your own testing.
