### ISSUE TITLE
UserGroupClient get_paged_groups returns User object

### ISSUE THREAD

**Issue by sachafaust** [okta/okta-sdk-python#75]
When calling get_paged_groups, the UserGroupClient returns User object instead of UserGroup object. Calling get_groups() works

**Comment by bretterer** [comment]
We have recently released a 1.x version of this SDK and all api calls and setup is different which should resolve this issue. Please check out our new version on PyPi.

This includes an update to our pagination of resources, so this appears to be resolved now.

If you find that you are still having an issue, please let us know if you are still having this issue.
