### ISSUE TITLE
NameError: name 'User' is not defined

### ISSUE THREAD

**Issue by natea** [okta/okta-sdk-python#76]
When I try to run the example code in the quickstart.rst, I get this error:

```
Traceback (most recent call last):
  File "create_client.py", line 6, in <module>
    new_user = User(login='example@example.com',
NameError: name 'User' is not defined
```

Here is the example code that I'm trying to execute:

```
from okta import UsersClient
# http://developer.okta.com/docs/api/getting_started/getting_a_token.html
usersClient = UsersClient('https://dev-212920-admin.okta.com',
                              'xxxxxxxxsxxxxxxxxxxxxxxxxxxx')
                              
new_user = User(login='example@example.com',
                    email='example@example.com',
                    firstName='Saml',
                    lastName='Jackson')
user = usersClient.create_user(new_user, activate=False)

user = usersClient.get_user('example@example.com')
usersClient.activate_user(user.id)

users = usersClient.get_paged_users()
while True:
    for user in users.result:
        print u"First Name: {}".format(user.profile.firstName)
        print u"Last Name:  {}".format(user.profile.lastName)
        print u"Login:      {}".format(user.profile.login)
        print u"User ID:    {}\n".format(user.id)
    if not users.is_last_page():
            # Keep on fetching pages of users until the last page
        users = usersClient.get_paged_users(url=users.next_url)
    else:
        break
```

**Comment by rdegges** [comment]
Ah! You're using the admin Org URL. You want to go to your dashboard homepage, then you'll see the Org URL value up at the top-right hand portion of your screen. That's the value you want to use in that UsersClient.

**Comment by Gauge73** [comment]
I ran into the same issue.  The initial reply seemed to be irrelevant, so I kept digging around in the module until I found what seems to be a solution.  Note that I'm a Python newb, so keep that in mind.  :)

The **User** class exists at **okta.models.user.User**.  So, here's what I did to instantiate a user:

`import okta

client = UsersClient('https://dev-123456-admin.okta.com', 'xxxxxxxxsxxxxxxxxxxxxxxxxxxx')
user = okta.models.user.User(login='user@domain.com', email='user@domain.com', firstName='Fred', lastName='Flintstone')
client.create_user(user, activate=False)
`

Hope this helps.

**Comment by bretterer** [comment]
We have recently released a 1.x version of this SDK and all api calls and setup is different which should resolve this issue. Please check out our new version on PyPi.

We have implemented a few checks around configuration to return better error messaging around this, however @rdegges is correct, the main issue here is that you are using the org url `dev-1234560-admin` but should be using `dev-123456` (without the `-admin`)

If you find that you are still having an issue, please let us know if you are still having this issue.
