### ISSUE TITLE
countryCode not included in UserProfile

### ISSUE THREAD

**Issue by Gauge73** [okta/okta-sdk-python#78]
**countryCode** should really be included as an argument of the UserProfile.  Really, all the default attributes should be, but this is specifically necessary for provisioning licenses in O365 (or so my O365 admin tells me).

It has to be added in the following places:

- As an attribute of the **UserProfile** class
- As a key/value pair (value str) in the **types** dictionary which is an attribute of the **UserProfile** class
- As an element of the **profile_attrs** list in the **__init__** method of the **User** class

I was able to make the above changes and successfully create users with the countryCode value as a kwarg when creating a User object.

**Comment by bretterer** [comment]
We have recently released a 1.x version of this SDK and all api calls and setup is different which should resolve this issue. Please check out our new version on PyPi.

This includes updates to the userProfile attributes that are available by default, however you are free to add any kind of attributes here during your api calls.

If you find that you are still having an issue, please let us know if you are still having this issue.
