### ISSUE TITLE
Full user profile

### ISSUE THREAD

**Issue by mwildehahn** [okta/okta-sdk-python#8]
It seems like the user profile only sets a subset of the profile fields.

Is there a way to get the full profile?

**Comment by argh128** [comment]
Looks like you can get this by modifying the userProfile https://github.com/okta/oktasdk-python/blob/master/okta/models/user/UserProfile.py and add the attributes your interested in the types area.

**Comment by coolnay309** [comment]
second that!

**Comment by cobaltjacket** [comment]
@argh128, that does appear to be the case, but this should be better supported first-party, particularly since some other Okta API modules (1st and 3rd party) have a lot more features.

**Comment by jmelberg-okta** [comment]
Hi @mhahn. We apologize for the long delay.

We are currently in the process of updating this project. As @argh128 mentioned, you can modify the the [`userProfile`](https://github.com/okta/oktasdk-python/blob/master/okta/models/user/UserProfile.py) to accommodate your needs. We will be pushing an update to ease this process soon!

Thanks!

**Comment by bretterer** [comment]
I am going to close this Issue as stale. We have recently released a 1.x version of this SDK and believe this is now resolved.

If you find that you are still having an issue, please let us know if you are still having this issue.
